package main

import (
	"github.com/akkagao/akka/gin-demo/route"
	"github.com/gin-gonic/gin"
	"github.com/thinkerou/favicon"
	// 增加swagger
	_ "./docs" // docs is generated by Swag CLI, you have to import it.
)

/**
启动gin服务
*/
func main() {
	engine := gin.Default()
	//gin.SetMode(gin.ReleaseMode)

	engine.Use(gin.Logger())
	// 设置图标
	engine.Use(favicon.New("./favicon.ico"))
	engine.StaticFile("/index", "./page/index.html")

	route.RouterInit(engine)
	engine.Run(":8088")
}
