// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 574fb16d86
// Version Date: 2019年 4月12日 星期五 00时42分59秒 UTC

package handlers

import (
	pb "github.com/akka/gokit-demo/hello"
)

// SayHello implements Service.
func SayHello(GreetingSayHello string) (*pb.HelloRequest, error) {
	request := pb.HelloRequest{
		Greeting: GreetingSayHello,
	}
	return &request, nil
}
