package main

import (
	"fmt"
	"log"

	"github.com/guonaihong/gout"
)

func main() {
	g := gout.New(nil)
	var httpCode int

	for key, value := range worlds {
		if err := g.GET(value).Code(&httpCode).Do(); err != nil {
			log.Fatal(err)
		}
		if httpCode != 200 {
			fmt.Println(fmt.Sprintf("http code:%v world:%v image:%v", httpCode, key, value))
		}
	}
}

var worlds = map[string]string{
	"3788_an":                         "http://reading-cdn.dubaner.com/resource/word/image/G1S1U1_an.png",
	"3789_a":                          "http://reading-cdn.dubaner.com/resource/word/image/G1S1U1_a.png",
	"3790_pencil":                     "http://reading-cdn.dubaner.com/resource/word/image/G1S1U1_pencil.png",
	"3791_ruler":                      "http://reading-cdn.dubaner.com/resource/word/image/G1S1U1_ruler.png",
	"3792_book":                       "http://reading-cdn.dubaner.com/resource/word/image/G1S1U1_book.png",
	"3793_have":                       "http://reading-cdn.dubaner.com/resource/word/image/G1S1U1_have.png",
	"3794_schoolbag":                  "http://reading-cdn.dubaner.com/resource/word/image/G1S1U1_schoolbag.png",
	"3795_I":                          "http://reading-cdn.dubaner.com/resource/word/image/G1S1U1_I.png",
	"3796_teacher":                    "http://reading-cdn.dubaner.com/resource/word/image/G1S1U1_teacher.png",
	"3797_is":                         "http://reading-cdn.dubaner.com/resource/word/image/G1S1U2_is.png",
	"3798_ear":                        "http://reading-cdn.dubaner.com/resource/word/image/G1S1U2_ear.png",
	"3799_mouth":                      "http://reading-cdn.dubaner.com/resource/word/image/G1S1U2_mouth.png",
	"3800_my":                         "http://reading-cdn.dubaner.com/resource/word/image/G1S1U2_my.png",
	"3801_eye":                        "http://reading-cdn.dubaner.com/resource/word/image/G1S1U2_eye.png",
	"3802_this":                       "http://reading-cdn.dubaner.com/resource/word/image/G1S1U2_this.png",
	"3803_face":                       "http://reading-cdn.dubaner.com/resource/word/image/G1S1U2_face.png",
	"3804_nose":                       "http://reading-cdn.dubaner.com/resource/word/image/G1S1U2_nose.png",
	"3805_bird":                       "http://reading-cdn.dubaner.com/resource/word/image/G1S1U3_bird.png",
	"3806_what":                       "http://reading-cdn.dubaner.com/resource/word/image/G1S1U3_what.png",
	"3807_cat":                        "http://reading-cdn.dubaner.com/resource/word/image/G1S1U3_cat.png",
	"3808_it":                         "http://reading-cdn.dubaner.com/resource/word/image/G1S1U3_it.png",
	"3809_dog":                        "http://reading-cdn.dubaner.com/resource/word/image/G1S1U3_dog.png",
	"3810_monkey":                     "http://reading-cdn.dubaner.com/resource/word/image/G1S1U3_monkey.png",
	"3811_tiger":                      "http://reading-cdn.dubaner.com/resource/word/image/G1S1U3_tiger.png",
	"3812_one":                        "http://reading-cdn.dubaner.com/resource/word/image/G1S1U4_one.png",
	"3813_five":                       "http://reading-cdn.dubaner.com/resource/word/image/G1S1U4_five.png",
	"3814_are":                        "http://reading-cdn.dubaner.com/resource/word/image/G1S1U4_are.png",
	"3815_four":                       "http://reading-cdn.dubaner.com/resource/word/image/G1S1U4_four.png",
	"3816_two":                        "http://reading-cdn.dubaner.com/resource/word/image/G1S1U4_two.png",
	"3817_seven":                      "http://reading-cdn.dubaner.com/resource/word/image/G1S1U4_seven.png",
	"3818_how":                        "http://reading-cdn.dubaner.com/resource/word/image/G1S1U4_how.png",
	"3819_six":                        "http://reading-cdn.dubaner.com/resource/word/image/G1S1U4_six.png",
	"3820_many":                       "http://reading-cdn.dubaner.com/resource/word/image/G1S1U4_many.png",
	"3821_ten":                        "http://reading-cdn.dubaner.com/resource/word/image/G1S1U4_ten.png",
	"3822_eight":                      "http://reading-cdn.dubaner.com/resource/word/image/G1S1U4_eight.png",
	"3823_there":                      "http://reading-cdn.dubaner.com/resource/word/image/G1S1U4_there.png",
	"3824_nine":                       "http://reading-cdn.dubaner.com/resource/word/image/G1S1U4_nine.png",
	"3825_three":                      "http://reading-cdn.dubaner.com/resource/word/image/G1S1U4_three.png",
	"3826_black":                      "http://reading-cdn.dubaner.com/resource/word/image/G1S1U5_black.png",
	"3827_green":                      "http://reading-cdn.dubaner.com/resource/word/image/G1S1U5_green.png",
	"3828_blue":                       "http://reading-cdn.dubaner.com/resource/word/image/G1S1U5_blue.png",
	"3829_red":                        "http://reading-cdn.dubaner.com/resource/word/image/G1S1U5_red.png",
	"3830_yellow":                     "http://reading-cdn.dubaner.com/resource/word/image/G1S1U5_yellow.png",
	"3831_colour":                     "http://reading-cdn.dubaner.com/resource/word/image/G1S1U5_colour.png",
	"3832_orange":                     "http://reading-cdn.dubaner.com/resource/word/image/G1S1U6_orange.png",
	"3833_pear":                       "http://reading-cdn.dubaner.com/resource/word/image/G1S1U6_pear.png",
	"3834_apple":                      "http://reading-cdn.dubaner.com/resource/word/image/G1S1U6_apple.png",
	"3835_banana":                     "http://reading-cdn.dubaner.com/resource/word/image/G1S1U6_banana.png",
	"3836_yes":                        "http://reading-cdn.dubaner.com/resource/word/image/G1S1U6_yes.png",
	"3837_you":                        "http://reading-cdn.dubaner.com/resource/word/image/G1S1U6_you.png",
	"3838_like":                       "http://reading-cdn.dubaner.com/resource/word/image/G1S1U6_like.png",
	"3839_do":                         "http://reading-cdn.dubaner.com/resource/word/image/G1S1U6_do.png",
	"3840_no":                         "http://reading-cdn.dubaner.com/resource/word/image/G1S1U6_no.png",
	"3841_on":                         "http://reading-cdn.dubaner.com/resource/word/image/G1S2U1_on.png",
	"3842_under":                      "http://reading-cdn.dubaner.com/resource/word/image/G1S2U1_under.png",
	"3843_blackboard":                 "http://reading-cdn.dubaner.com/resource/word/image/G1S2U1_blackboard.png",
	"3844_where":                      "http://reading-cdn.dubaner.com/resource/word/image/G1S2U1_where.png",
	"3845_in":                         "http://reading-cdn.dubaner.com/resource/word/image/G1S2U1_in.png",
	"3846_chair":                      "http://reading-cdn.dubaner.com/resource/word/image/G1S2U1_chair.png",
	"3847_desk":                       "http://reading-cdn.dubaner.com/resource/word/image/G1S2U1_desk.png",
	"3848_the":                        "http://reading-cdn.dubaner.com/resource/word/image/G1S2U1_the.png",
	"3849_bed":                        "http://reading-cdn.dubaner.com/resource/word/image/G1S2U2_bed.png",
	"3850_behind":                     "http://reading-cdn.dubaner.com/resource/word/image/G1S2U2_behind.png",
	"3851_box":                        "http://reading-cdn.dubaner.com/resource/word/image/G1S2U2_box.png",
	"3852_light":                      "http://reading-cdn.dubaner.com/resource/word/image/G1S2U2_light.png",
	"3853_door":                       "http://reading-cdn.dubaner.com/resource/word/image/G1S2U2_door.png",
	"3854_near":                       "http://reading-cdn.dubaner.com/resource/word/image/G1S2U2_near.png",
	"3855_train":                      "http://reading-cdn.dubaner.com/resource/word/image/G1S2U3_train.png",
	"3856_plane":                      "http://reading-cdn.dubaner.com/resource/word/image/G1S2U3_plane.png",
	"3857_ball":                       "http://reading-cdn.dubaner.com/resource/word/image/G1S2U3_ball.png",
	"3858_bear":                       "http://reading-cdn.dubaner.com/resource/word/image/G1S2U3_bear.png",
	"3859_can":                        "http://reading-cdn.dubaner.com/resource/word/image/G1S2U3_can.png",
	"3860_car":                        "http://reading-cdn.dubaner.com/resource/word/image/G1S2U3_car.png",
	"3861_sorry":                      "http://reading-cdn.dubaner.com/resource/word/image/G1S2U3_sorry.png",
	"3862_sure":                       "http://reading-cdn.dubaner.com/resource/word/image/G1S2U3_sure.png",
	"3863_doll":                       "http://reading-cdn.dubaner.com/resource/word/image/G1S2U3_doll.png",
	"3864_fish":                       "http://reading-cdn.dubaner.com/resource/word/image/G1S2U4_fish.png",
	"3865_and":                        "http://reading-cdn.dubaner.com/resource/word/image/G1S2U4_and.png",
	"3866_vegetable":                  "http://reading-cdn.dubaner.com/resource/word/image/G1S2U4_vegetable.png",
	"3867_want":                       "http://reading-cdn.dubaner.com/resource/word/image/G1S2U4_want.png",
	"3868_rice":                       "http://reading-cdn.dubaner.com/resource/word/image/G1S2U4_rice.png",
	"3869_hungry":                     "http://reading-cdn.dubaner.com/resource/word/image/G1S2U4_hungry.png",
	"3870_chicken":                    "http://reading-cdn.dubaner.com/resource/word/image/G1S2U4_chicken.png",
	"3871_noodles":                    "http://reading-cdn.dubaner.com/resource/word/image/G1S2U4_noodles.png",
	"3872_water":                      "http://reading-cdn.dubaner.com/resource/word/image/G1S2U5_water.png",
	"3873_juice":                      "http://reading-cdn.dubaner.com/resource/word/image/G1S2U5_juice.png",
	"3874_tea":                        "http://reading-cdn.dubaner.com/resource/word/image/G1S2U5_tea.png",
	"3875_milk":                       "http://reading-cdn.dubaner.com/resource/word/image/G1S2U5_milk.png",
	"3876_thanks":                     "http://reading-cdn.dubaner.com/resource/word/image/G1S2U5_thanks.png",
	"3877_thirsty":                    "http://reading-cdn.dubaner.com/resource/word/image/G1S2U5_thirsty.png",
	"3878_T-shirt":                    "http://reading-cdn.dubaner.com/resource/word/image/G1S2U6_T-shirt.png",
	"3879_your":                       "http://reading-cdn.dubaner.com/resource/word/image/G1S2U6_your.png",
	"3880_shirt":                      "http://reading-cdn.dubaner.com/resource/word/image/G1S2U6_shirt.png",
	"3881_shorts":                     "http://reading-cdn.dubaner.com/resource/word/image/G1S2U6_shorts.png",
	"3882_skirt":                      "http://reading-cdn.dubaner.com/resource/word/image/G1S2U6_skirt.png",
	"3883_socks":                      "http://reading-cdn.dubaner.com/resource/word/image/G1S2U6_socks.png",
	"3884_dress":                      "http://reading-cdn.dubaner.com/resource/word/image/G1S2U6_dress.png",
	"3885_father":                     "http://reading-cdn.dubaner.com/resource/word/image/G2S1U1_father.png",
	"3886_grandfather":                "http://reading-cdn.dubaner.com/resource/word/image/G2S1U1_grandfather.png",
	"3887_grandmother":                "http://reading-cdn.dubaner.com/resource/word/image/G2S1U1_grandmother.png",
	"3888_who":                        "http://reading-cdn.dubaner.com/resource/word/image/G2S1U1_who.png",
	"3889_he":                         "http://reading-cdn.dubaner.com/resource/word/image/G2S1U1_he.png",
	"3890_brother":                    "http://reading-cdn.dubaner.com/resource/word/image/G2S1U1_brother.png",
	"3891_she":                        "http://reading-cdn.dubaner.com/resource/word/image/G2S1U1_she.png",
	"3892_sister":                     "http://reading-cdn.dubaner.com/resource/word/image/G2S1U1_sister.png",
	"3893_mother":                     "http://reading-cdn.dubaner.com/resource/word/image/G2S1U1_mother.png",
	"3894_or":                         "http://reading-cdn.dubaner.com/resource/word/image/G2S1U2_or.png",
	"3895_friend":                     "http://reading-cdn.dubaner.com/resource/word/image/G2S1U2_friend.png",
	"3896_girl":                       "http://reading-cdn.dubaner.com/resource/word/image/G2S1U2_girl.png",
	"3897_boy":                        "http://reading-cdn.dubaner.com/resource/word/image/G2S1U2_boy.png",
	"3898_woman":                      "http://reading-cdn.dubaner.com/resource/word/image/G2S1U2_woman.png",
	"3899_her":                        "http://reading-cdn.dubaner.com/resource/word/image/G2S1U2_her.png",
	"3900_his":                        "http://reading-cdn.dubaner.com/resource/word/image/G2S1U2_his.png",
	"3901_classmate":                  "http://reading-cdn.dubaner.com/resource/word/image/G2S1U2_classmate.png",
	"3902_look":                       "http://reading-cdn.dubaner.com/resource/word/image/G2S1U2_look.png",
	"3903_man":                        "http://reading-cdn.dubaner.com/resource/word/image/G2S1U2_man.png",
	"3904_name":                       "http://reading-cdn.dubaner.com/resource/word/image/G2S1U2_name.png",
	"3905_big":                        "http://reading-cdn.dubaner.com/resource/word/image/G2S1U3_big.png",
	"3906_pretty":                     "http://reading-cdn.dubaner.com/resource/word/image/G2S1U3_pretty.png",
	"3907_handsome":                   "http://reading-cdn.dubaner.com/resource/word/image/G2S1U3_handsome.png",
	"3908_short":                      "http://reading-cdn.dubaner.com/resource/word/image/G2S1U3_short.png",
	"3909_does":                       "http://reading-cdn.dubaner.com/resource/word/image/G2S1U3_does.png",
	"3910_tall":                       "http://reading-cdn.dubaner.com/resource/word/image/G2S1U3_tall.png",
	"3911_new":                        "http://reading-cdn.dubaner.com/resource/word/image/G2S1U3_new.png",
	"3912_thin":                       "http://reading-cdn.dubaner.com/resource/word/image/G2S1U3_thin.png",
	"3913_park":                       "http://reading-cdn.dubaner.com/resource/word/image/G2S1U4_park.png",
	"3914_go":                         "http://reading-cdn.dubaner.com/resource/word/image/G2S1U4_go.png",
	"3915_bookshop":                   "http://reading-cdn.dubaner.com/resource/word/image/G2S1U4_bookshop.png",
	"3916_school":                     "http://reading-cdn.dubaner.com/resource/word/image/G2S1U4_school.png",
	"3917_zoo":                        "http://reading-cdn.dubaner.com/resource/word/image/G2S1U4_zoo.png",
	"3918_hospital":                   "http://reading-cdn.dubaner.com/resource/word/image/G2S1U4_hospital.png",
	"3919_supermarket":                "http://reading-cdn.dubaner.com/resource/word/image/G2S1U4_supermarket.png",
	"3920_to":                         "http://reading-cdn.dubaner.com/resource/word/image/G2S1U4_to.png",
	"3921_tree":                       "http://reading-cdn.dubaner.com/resource/word/image/G2S1U5_tree.png",
	"3922_flower":                     "http://reading-cdn.dubaner.com/resource/word/image/G2S1U5_flower.png",
	"3923_grass":                      "http://reading-cdn.dubaner.com/resource/word/image/G2S1U5_grass.png",
	"3924_boat":                       "http://reading-cdn.dubaner.com/resource/word/image/G2S1U5_boat.png",
	"3925_hill":                       "http://reading-cdn.dubaner.com/resource/word/image/G2S1U5_hill.png",
	"3926_lake":                       "http://reading-cdn.dubaner.com/resource/word/image/G2S1U5_lake.png",
	"3927_Father Christmas":           "http://reading-cdn.dubaner.com/resource/word/image/G2S1U6_Father_Christmas.png",
	"3928_too":                        "http://reading-cdn.dubaner.com/resource/word/image/G2S1U6_too.png",
	"3929_for":                        "http://reading-cdn.dubaner.com/resource/word/image/G2S1U6_for.png",
	"3930_present":                    "http://reading-cdn.dubaner.com/resource/word/image/G2S1U6_present.png",
	"3931_happy":                      "http://reading-cdn.dubaner.com/resource/word/image/G2S1U6_happy.png",
	"3932_here":                       "http://reading-cdn.dubaner.com/resource/word/image/G2S1U6_here.png",
	"3933_card":                       "http://reading-cdn.dubaner.com/resource/word/image/G2S1U6_card.png",
	"3934_Christmas":                  "http://reading-cdn.dubaner.com/resource/word/image/G2S1U6_Christmas.png",
	"3935_Christmas tree":             "http://reading-cdn.dubaner.com/resource/word/image/G2S1U6_Christmas_tree.png",
	"3936_merry":                      "http://reading-cdn.dubaner.com/resource/word/image/G2S1U6_merry.png",
	"3937_thank":                      "http://reading-cdn.dubaner.com/resource/word/image/G2S1U6_thank.png",
	"3938_New Year":                   "http://reading-cdn.dubaner.com/resource/word/image/G2S1U6_New_Year.png",
	"3939_fly a kite":                 "http://reading-cdn.dubaner.com/resource/word/image/G2S2U1_fly_a_kite.png",
	"3940_play football":              "http://reading-cdn.dubaner.com/resource/word/image/G2S2U1_play_football.png",
	"3941_ride a bike":                "http://reading-cdn.dubaner.com/resource/word/image/G2S2U1_ride_a_bike.png",
	"3942_can't":                      "http://reading-cdn.dubaner.com/resource/word/image/G2S2U1_can't.png",
	"3943_make a model plane":         "http://reading-cdn.dubaner.com/resource/word/image/G2S2U1_make_a_model_plane.png",
	"3944_make a snowman":             "http://reading-cdn.dubaner.com/resource/word/image/G2S2U1_make_a_snowman.png",
	"3945_swim":                       "http://reading-cdn.dubaner.com/resource/word/image/G2S2U1_swim.png",
	"3946_umbrella":                   "http://reading-cdn.dubaner.com/resource/word/image/G2S2U2_umbrella.png",
	"3947_weather":                    "http://reading-cdn.dubaner.com/resource/word/image/G2S2U2_weather.png",
	"3948_rainy":                      "http://reading-cdn.dubaner.com/resource/word/image/G2S2U2_rainy.png",
	"3949_windy":                      "http://reading-cdn.dubaner.com/resource/word/image/G2S2U2_windy.png",
	"3950_wow":                        "http://reading-cdn.dubaner.com/resource/word/image/G2S2U2_wow.png",
	"3951_snowy":                      "http://reading-cdn.dubaner.com/resource/word/image/G2S2U2_snowy.png",
	"3952_cloudy":                     "http://reading-cdn.dubaner.com/resource/word/image/G2S2U2_cloudy.png",
	"3953_let's":                      "http://reading-cdn.dubaner.com/resource/word/image/G2S2U2_let's.png",
	"3954_sunny":                      "http://reading-cdn.dubaner.com/resource/word/image/G2S2U2_sunny.png",
	"3955_favourite":                  "http://reading-cdn.dubaner.com/resource/word/image/G2S2U3_favourite.png",
	"3956_autumn":                     "http://reading-cdn.dubaner.com/resource/word/image/G2S2U3_autumn.png",
	"3957_warm":                       "http://reading-cdn.dubaner.com/resource/word/image/G2S2U3_warm.png",
	"3958_winter":                     "http://reading-cdn.dubaner.com/resource/word/image/G2S2U3_winter.png",
	"3959_season":                     "http://reading-cdn.dubaner.com/resource/word/image/G2S2U3_season.png",
	"3960_hot":                        "http://reading-cdn.dubaner.com/resource/word/image/G2S2U3_hot.png",
	"3961_spring":                     "http://reading-cdn.dubaner.com/resource/word/image/G2S2U3_spring.png",
	"3962_cold":                       "http://reading-cdn.dubaner.com/resource/word/image/G2S2U3_cold.png",
	"3963_cool":                       "http://reading-cdn.dubaner.com/resource/word/image/G2S2U3_cool.png",
	"3964_summer":                     "http://reading-cdn.dubaner.com/resource/word/image/G2S2U3_summer.png",
	"3965_fifteen":                    "http://reading-cdn.dubaner.com/resource/word/image/G2S2U4_fifteen.png",
	"3966_fifty":                      "http://reading-cdn.dubaner.com/resource/word/image/G2S2U4_fifty.png",
	"3967_twelve":                     "http://reading-cdn.dubaner.com/resource/word/image/G2S2U4_twelve.png",
	"3968_twenty":                     "http://reading-cdn.dubaner.com/resource/word/image/G2S2U4_twenty.png",
	"3969_forty":                      "http://reading-cdn.dubaner.com/resource/word/image/G2S2U4_forty.png",
	"3970_fourteen":                   "http://reading-cdn.dubaner.com/resource/word/image/G2S2U4_fourteen.png",
	"3971_playtime":                   "http://reading-cdn.dubaner.com/resource/word/image/G2S2U4_playtime.png",
	"3972_eleven":                     "http://reading-cdn.dubaner.com/resource/word/image/G2S2U4_eleven.png",
	"3973_thirteen":                   "http://reading-cdn.dubaner.com/resource/word/image/G2S2U4_thirteen.png",
	"3974_thirty":                     "http://reading-cdn.dubaner.com/resource/word/image/G2S2U4_thirty.png",
	"3975_time":                       "http://reading-cdn.dubaner.com/resource/word/image/G2S2U4_time.png",
	"3976_at":                         "http://reading-cdn.dubaner.com/resource/word/image/G2S2U5_at.png",
	"3977_get up":                     "http://reading-cdn.dubaner.com/resource/word/image/G2S2U5_get_up.png",
	"3978_go home":                    "http://reading-cdn.dubaner.com/resource/word/image/G2S2U5_go_home.png",
	"3979_go to bed":                  "http://reading-cdn.dubaner.com/resource/word/image/G2S2U5_go_to_bed.png",
	"3980_go to school":               "http://reading-cdn.dubaner.com/resource/word/image/G2S2U5_go_to_school.png",
	"3981_when":                       "http://reading-cdn.dubaner.com/resource/word/image/G2S2U5_when.png",
	"3982_eat breakfast":              "http://reading-cdn.dubaner.com/resource/word/image/G2S2U5_eat_breakfast.png",
	"3983_eat dinner":                 "http://reading-cdn.dubaner.com/resource/word/image/G2S2U5_eat_dinner.png",
	"3984_eat lunch":                  "http://reading-cdn.dubaner.com/resource/word/image/G2S2U5_eat_lunch.png",
	"3985_every day":                  "http://reading-cdn.dubaner.com/resource/word/image/G2S2U5_every_day.png",
	"3986_today":                      "http://reading-cdn.dubaner.com/resource/word/image/G2S2U6_today.png",
	"3987_Tuesday":                    "http://reading-cdn.dubaner.com/resource/word/image/G2S2U6_Tuesday.png",
	"3988_Friday":                     "http://reading-cdn.dubaner.com/resource/word/image/G2S2U6_Friday.png",
	"3989_Wednesday":                  "http://reading-cdn.dubaner.com/resource/word/image/G2S2U6_Wednesday.png",
	"3990_Saturday":                   "http://reading-cdn.dubaner.com/resource/word/image/G2S2U6_Saturday.png",
	"3991_Sunday":                     "http://reading-cdn.dubaner.com/resource/word/image/G2S2U6_Sunday.png",
	"3992_Monday":                     "http://reading-cdn.dubaner.com/resource/word/image/G2S2U6_Monday.png",
	"3993_Thursday":                   "http://reading-cdn.dubaner.com/resource/word/image/G2S2U6_Thursday.png",
	"3994_old":                        "http://reading-cdn.dubaner.com/resource/word/image/G3S1U1_old.png",
	"3995_age":                        "http://reading-cdn.dubaner.com/resource/word/image/G3S1U1_age.png",
	"3996_grade":                      "http://reading-cdn.dubaner.com/resource/word/image/G3S1U1_grade.png",
	"3997_year":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S1U1_year.png",
	"3998_your":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S1U1_your.png",
	"3999_how old":                    "http://reading-cdn.dubaner.com/resource/word/image/G3S1U1_how_old.png",
	"4000_class":                      "http://reading-cdn.dubaner.com/resource/word/image/G3S1U1_class.png",
	"4001_dear":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S1U1_dear.png",
	"4002_my":                         "http://reading-cdn.dubaner.com/resource/word/image/G3S1U1_my.png",
	"4003_name":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S1U1_name.png",
	"4004_new":                        "http://reading-cdn.dubaner.com/resource/word/image/G3S1U1_new.png",
	"4005_tongue":                     "http://reading-cdn.dubaner.com/resource/word/image/G3S1U2_tongue.png",
	"4006_afternoon":                  "http://reading-cdn.dubaner.com/resource/word/image/G3S1U2_afternoon.png",
	"4007_foot(feet)":                 "http://reading-cdn.dubaner.com/resource/word/image/G3S1U2_foot(feet).png",
	"4008_arm":                        "http://reading-cdn.dubaner.com/resource/word/image/G3S1U2_arm.png",
	"4009_bad":                        "http://reading-cdn.dubaner.com/resource/word/image/G3S1U2_bad.png",
	"4010_bite":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S1U2_bite.png",
	"4011_body":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S1U2_body.png",
	"4012_hair":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S1U2_hair.png",
	"4013_hand":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S1U2_hand.png",
	"4014_head":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S1U2_head.png",
	"4015_help":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S1U2_help.png",
	"4016_hurt":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S1U2_hurt.png",
	"4017_kick":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S1U2_kick.png",
	"4018_leg":                        "http://reading-cdn.dubaner.com/resource/word/image/G3S1U2_leg.png",
	"4019_summary":                    "http://reading-cdn.dubaner.com/resource/word/image/G3S1U2_summary.png",
	"4020_ear":                        "http://reading-cdn.dubaner.com/resource/word/image/G3S1U2_ear.png",
	"4021_morning":                    "http://reading-cdn.dubaner.com/resource/word/image/G3S1U2_morning.png",
	"4022_mouth":                      "http://reading-cdn.dubaner.com/resource/word/image/G3S1U2_mouth.png",
	"4023_the matter":                 "http://reading-cdn.dubaner.com/resource/word/image/G3S1U2_the_matter.png",
	"4024_eye":                        "http://reading-cdn.dubaner.com/resource/word/image/G3S1U2_eye.png",
	"4025_face":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S1U2_face.png",
	"4026_nose":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S1U2_nose.png",
	"4027_tomato":                     "http://reading-cdn.dubaner.com/resource/word/image/G3S1U3_tomato.png",
	"4028_fish":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S1U3_fish.png",
	"4029_for":                        "http://reading-cdn.dubaner.com/resource/word/image/G3S1U3_for.png",
	"4030_vegetables":                 "http://reading-cdn.dubaner.com/resource/word/image/G3S1U3_vegetables.png",
	"4031_fruit":                      "http://reading-cdn.dubaner.com/resource/word/image/G3S1U3_fruit.png",
	"4032_potato":                     "http://reading-cdn.dubaner.com/resource/word/image/G3S1U3_potato.png",
	"4033_rice":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S1U3_rice.png",
	"4034_bread":                      "http://reading-cdn.dubaner.com/resource/word/image/G3S1U3_bread.png",
	"4035_buy":                        "http://reading-cdn.dubaner.com/resource/word/image/G3S1U3_buy.png",
	"4036_cake":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S1U3_cake.png",
	"4037_shopping list":              "http://reading-cdn.dubaner.com/resource/word/image/G3S1U3_shopping_list.png",
	"4038_ice-cream":                  "http://reading-cdn.dubaner.com/resource/word/image/G3S1U3_ice-cream.png",
	"4039_chicken":                    "http://reading-cdn.dubaner.com/resource/word/image/G3S1U3_chicken.png",
	"4040_cola":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S1U3_cola.png",
	"4041_meat":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S1U3_meat.png",
	"4042_egg":                        "http://reading-cdn.dubaner.com/resource/word/image/G3S1U3_egg.png",
	"4043_noodles":                    "http://reading-cdn.dubaner.com/resource/word/image/G3S1U3_noodles.png",
	"4044_fish":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S1U4_fish.png",
	"4045_turtle":                     "http://reading-cdn.dubaner.com/resource/word/image/G3S1U4_turtle.png",
	"4046_pet":                        "http://reading-cdn.dubaner.com/resource/word/image/G3S1U4_pet.png",
	"4047_big":                        "http://reading-cdn.dubaner.com/resource/word/image/G3S1U4_big.png",
	"4048_bird":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S1U4_bird.png",
	"4049_rabbit":                     "http://reading-cdn.dubaner.com/resource/word/image/G3S1U4_rabbit.png",
	"4050_short":                      "http://reading-cdn.dubaner.com/resource/word/image/G3S1U4_short.png",
	"4051_cat":                        "http://reading-cdn.dubaner.com/resource/word/image/G3S1U4_cat.png",
	"4052_chicken":                    "http://reading-cdn.dubaner.com/resource/word/image/G3S1U4_chicken.png",
	"4053_small":                      "http://reading-cdn.dubaner.com/resource/word/image/G3S1U4_small.png",
	"4054_snake":                      "http://reading-cdn.dubaner.com/resource/word/image/G3S1U4_snake.png",
	"4055_long":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S1U4_long.png",
	"4056_look for":                   "http://reading-cdn.dubaner.com/resource/word/image/G3S1U4_look_for.png",
	"4057_dance":                      "http://reading-cdn.dubaner.com/resource/word/image/G3S1U4_dance.png",
	"4058_tail":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S1U4_tail.png",
	"4059_dog":                        "http://reading-cdn.dubaner.com/resource/word/image/G3S1U4_dog.png",
	"4060_monkey":                     "http://reading-cdn.dubaner.com/resource/word/image/G3S1U4_monkey.png",
	"4061_duck":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S1U4_duck.png",
	"4062_tiger":                      "http://reading-cdn.dubaner.com/resource/word/image/G3S1U4_tiger.png",
	"4063_trousers":                   "http://reading-cdn.dubaner.com/resource/word/image/G3S1U5_trousers.png",
	"4064_T-shirt":                    "http://reading-cdn.dubaner.com/resource/word/image/G3S1U5_T-shirt.png",
	"4065_gloves":                     "http://reading-cdn.dubaner.com/resource/word/image/G3S1U5_gloves.png",
	"4066_wear":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S1U5_wear.png",
	"4067_week":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S1U5_week.png",
	"4068_shirt":                      "http://reading-cdn.dubaner.com/resource/word/image/G3S1U5_shirt.png",
	"4069_shoes":                      "http://reading-cdn.dubaner.com/resource/word/image/G3S1U5_shoes.png",
	"4070_shorts":                     "http://reading-cdn.dubaner.com/resource/word/image/G3S1U5_shorts.png",
	"4071_cap":                        "http://reading-cdn.dubaner.com/resource/word/image/G3S1U5_cap.png",
	"4072_should":                     "http://reading-cdn.dubaner.com/resource/word/image/G3S1U5_should.png",
	"4073_skirt":                      "http://reading-cdn.dubaner.com/resource/word/image/G3S1U5_skirt.png",
	"4074_jacket":                     "http://reading-cdn.dubaner.com/resource/word/image/G3S1U5_jacket.png",
	"4075_socks":                      "http://reading-cdn.dubaner.com/resource/word/image/G3S1U5_socks.png",
	"4076_soon":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S1U5_soon.png",
	"4077_coat":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S1U5_coat.png",
	"4078_look forward to":            "http://reading-cdn.dubaner.com/resource/word/image/G3S1U5_look_forward_to.png",
	"4079_sweater":                    "http://reading-cdn.dubaner.com/resource/word/image/G3S1U5_sweater.png",
	"4080_dress":                      "http://reading-cdn.dubaner.com/resource/word/image/G3S1U5_dress.png",
	"4081_February":                   "http://reading-cdn.dubaner.com/resource/word/image/G3S1U6_February.png",
	"4082_first":                      "http://reading-cdn.dubaner.com/resource/word/image/G3S1U6_first.png",
	"4083_party":                      "http://reading-cdn.dubaner.com/resource/word/image/G3S1U6_party.png",
	"4084_April":                      "http://reading-cdn.dubaner.com/resource/word/image/G3S1U6_April.png",
	"4085_August":                     "http://reading-cdn.dubaner.com/resource/word/image/G3S1U6_August.png",
	"4086_birthday":                   "http://reading-cdn.dubaner.com/resource/word/image/G3S1U6_birthday.png",
	"4087_September":                  "http://reading-cdn.dubaner.com/resource/word/image/G3S1U6_September.png",
	"4088_January":                    "http://reading-cdn.dubaner.com/resource/word/image/G3S1U6_January.png",
	"4089_July":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S1U6_July.png",
	"4090_June":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S1U6_June.png",
	"4091_December":                   "http://reading-cdn.dubaner.com/resource/word/image/G3S1U6_December.png",
	"4092_delicious":                  "http://reading-cdn.dubaner.com/resource/word/image/G3S1U6_delicious.png",
	"4093_March":                      "http://reading-cdn.dubaner.com/resource/word/image/G3S1U6_March.png",
	"4094_May":                        "http://reading-cdn.dubaner.com/resource/word/image/G3S1U6_May.png",
	"4095_November":                   "http://reading-cdn.dubaner.com/resource/word/image/G3S1U6_November.png",
	"4096_October":                    "http://reading-cdn.dubaner.com/resource/word/image/G3S1U6_October.png",
	"4097_PE":                         "http://reading-cdn.dubaner.com/resource/word/image/G3S2U1_PE.png",
	"4098_art":                        "http://reading-cdn.dubaner.com/resource/word/image/G3S2U1_art.png",
	"4099_we":                         "http://reading-cdn.dubaner.com/resource/word/image/G3S2U1_we.png",
	"4100_science":                    "http://reading-cdn.dubaner.com/resource/word/image/G3S2U1_science.png",
	"4101_Chinese":                    "http://reading-cdn.dubaner.com/resource/word/image/G3S2U1_Chinese.png",
	"4102_computer class":             "http://reading-cdn.dubaner.com/resource/word/image/G3S2U1_computer_class.png",
	"4103_maths":                      "http://reading-cdn.dubaner.com/resource/word/image/G3S2U1_maths.png",
	"4104_that":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S2U1_that.png",
	"4105_music":                      "http://reading-cdn.dubaner.com/resource/word/image/G3S2U1_music.png",
	"4106_English":                    "http://reading-cdn.dubaner.com/resource/word/image/G3S2U1_English.png",
	"4107_toilet":                     "http://reading-cdn.dubaner.com/resource/word/image/G3S2U2_toilet.png",
	"4108_our":                        "http://reading-cdn.dubaner.com/resource/word/image/G3S2U2_our.png",
	"4109_first":                      "http://reading-cdn.dubaner.com/resource/word/image/G3S2U2_first.png",
	"4110_floor":                      "http://reading-cdn.dubaner.com/resource/word/image/G3S2U2_floor.png",
	"4111_playground":                 "http://reading-cdn.dubaner.com/resource/word/image/G3S2U2_playground.png",
	"4112_room":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S2U2_room.png",
	"4113_blackboard":                 "http://reading-cdn.dubaner.com/resource/word/image/G3S2U2_blackboard.png",
	"4114_second":                     "http://reading-cdn.dubaner.com/resource/word/image/G3S2U2_second.png",
	"4115_chair":                      "http://reading-cdn.dubaner.com/resource/word/image/G3S2U2_chair.png",
	"4116_classroom":                  "http://reading-cdn.dubaner.com/resource/word/image/G3S2U2_classroom.png",
	"4117_library":                    "http://reading-cdn.dubaner.com/resource/word/image/G3S2U2_library.png",
	"4118_desk":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S2U2_desk.png",
	"4119_they":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S2U2_they.png",
	"4120_third":                      "http://reading-cdn.dubaner.com/resource/word/image/G3S2U2_third.png",
	"4121_tomorrow":                   "http://reading-cdn.dubaner.com/resource/word/image/G3S2U3_tomorrow.png",
	"4122_after school":               "http://reading-cdn.dubaner.com/resource/word/image/G3S2U3_after_school.png",
	"4123_fly a kite":                 "http://reading-cdn.dubaner.com/resource/word/image/G3S2U3_fly_a_kite.png",
	"4124_play chess":                 "http://reading-cdn.dubaner.com/resource/word/image/G3S2U3_play_chess.png",
	"4125_play football":              "http://reading-cdn.dubaner.com/resource/word/image/G3S2U3_play_football.png",
	"4126_play sports":                "http://reading-cdn.dubaner.com/resource/word/image/G3S2U3_play_sports.png",
	"4127_wake up":                    "http://reading-cdn.dubaner.com/resource/word/image/G3S2U3_wake_up.png",
	"4128_be back":                    "http://reading-cdn.dubaner.com/resource/word/image/G3S2U3_be_back.png",
	"4129_ride a bike":                "http://reading-cdn.dubaner.com/resource/word/image/G3S2U3_ride_a_bike.png",
	"4130_read books":                 "http://reading-cdn.dubaner.com/resource/word/image/G3S2U3_read_books.png",
	"4131_really":                     "http://reading-cdn.dubaner.com/resource/word/image/G3S2U3_really.png",
	"4132_sing songs":                 "http://reading-cdn.dubaner.com/resource/word/image/G3S2U3_sing_songs.png",
	"4133_dance":                      "http://reading-cdn.dubaner.com/resource/word/image/G3S2U3_dance.png",
	"4134_make a model plane":         "http://reading-cdn.dubaner.com/resource/word/image/G3S2U3_make_a_model_plane.png",
	"4135_make a snowman":             "http://reading-cdn.dubaner.com/resource/word/image/G3S2U3_make_a_snowman.png",
	"4136_swim":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S2U3_swim.png",
	"4137_draw pictures":              "http://reading-cdn.dubaner.com/resource/word/image/G3S2U3_draw_pictures.png",
	"4138_father":                     "http://reading-cdn.dubaner.com/resource/word/image/G3S2U4_father.png",
	"4139_OK":                         "http://reading-cdn.dubaner.com/resource/word/image/G3S2U4_OK.png",
	"4140_uncle":                      "http://reading-cdn.dubaner.com/resource/word/image/G3S2U4_uncle.png",
	"4141_aunt":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S2U4_aunt.png",
	"4142_beautiful":                  "http://reading-cdn.dubaner.com/resource/word/image/G3S2U4_beautiful.png",
	"4143_water bottle":               "http://reading-cdn.dubaner.com/resource/word/image/G3S2U4_water_bottle.png",
	"4144_welcome":                    "http://reading-cdn.dubaner.com/resource/word/image/G3S2U4_welcome.png",
	"4145_grandfather":                "http://reading-cdn.dubaner.com/resource/word/image/G3S2U4_grandfather.png",
	"4146_handsome":                   "http://reading-cdn.dubaner.com/resource/word/image/G3S2U4_handsome.png",
	"4147_brother":                    "http://reading-cdn.dubaner.com/resource/word/image/G3S2U4_brother.png",
	"4148_sister":                     "http://reading-cdn.dubaner.com/resource/word/image/G3S2U4_sister.png",
	"4149_know":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S2U4_know.png",
	"4150_cousin":                     "http://reading-cdn.dubaner.com/resource/word/image/G3S2U4_cousin.png",
	"4151_lost":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S2U4_lost.png",
	"4152_mother":                     "http://reading-cdn.dubaner.com/resource/word/image/G3S2U4_mother.png",
	"4153_much":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S2U4_much.png",
	"4154_family":                     "http://reading-cdn.dubaner.com/resource/word/image/G3S2U4_family.png",
	"4155_feeding the fish":           "http://reading-cdn.dubaner.com/resource/word/image/G3S2U5_feeding_the_fish.png",
	"4156_play with":                  "http://reading-cdn.dubaner.com/resource/word/image/G3S2U5_play_with.png",
	"4157_walking the dog":            "http://reading-cdn.dubaner.com/resource/word/image/G3S2U5_walking_the_dog.png",
	"4158_watching TV":                "http://reading-cdn.dubaner.com/resource/word/image/G3S2U5_watching_TV.png",
	"4159_watering the plants":        "http://reading-cdn.dubaner.com/resource/word/image/G3S2U5_watering_the_plants.png",
	"4160_run":                        "http://reading-cdn.dubaner.com/resource/word/image/G3S2U5_run.png",
	"4161_in one hour":                "http://reading-cdn.dubaner.com/resource/word/image/G3S2U5_in_one_hour.png",
	"4162_children":                   "http://reading-cdn.dubaner.com/resource/word/image/G3S2U5_children.png",
	"4163_cleaning the room":          "http://reading-cdn.dubaner.com/resource/word/image/G3S2U5_cleaning_the_room.png",
	"4164_cooking dinner":             "http://reading-cdn.dubaner.com/resource/word/image/G3S2U5_cooking_dinner.png",
	"4165_listening to music":         "http://reading-cdn.dubaner.com/resource/word/image/G3S2U5_listening_to_music.png",
	"4166_everyone":                   "http://reading-cdn.dubaner.com/resource/word/image/G3S2U5_everyone.png",
	"4167_for rent":                   "http://reading-cdn.dubaner.com/resource/word/image/G3S2U6_for_rent.png",
	"4168_bathroom":                   "http://reading-cdn.dubaner.com/resource/word/image/G3S2U6_bathroom.png",
	"4169_bed":                        "http://reading-cdn.dubaner.com/resource/word/image/G3S2U6_bed.png",
	"4170_bedroom":                    "http://reading-cdn.dubaner.com/resource/word/image/G3S2U6_bedroom.png",
	"4171_box":                        "http://reading-cdn.dubaner.com/resource/word/image/G3S2U6_box.png",
	"4172_home":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S2U6_home.png",
	"4173_sofa":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S2U6_sofa.png",
	"4174_kitchen":                    "http://reading-cdn.dubaner.com/resource/word/image/G3S2U6_kitchen.png",
	"4175_light":                      "http://reading-cdn.dubaner.com/resource/word/image/G3S2U6_light.png",
	"4176_living room":                "http://reading-cdn.dubaner.com/resource/word/image/G3S2U6_living_room.png",
	"4177_study":                      "http://reading-cdn.dubaner.com/resource/word/image/G3S2U6_study.png",
	"4178_dining room":                "http://reading-cdn.dubaner.com/resource/word/image/G3S2U6_dining_room.png",
	"4179_door":                       "http://reading-cdn.dubaner.com/resource/word/image/G3S2U6_door.png",
	"4180_father":                     "http://reading-cdn.dubaner.com/resource/word/image/G4S1U1_father.png",
	"4181_often":                      "http://reading-cdn.dubaner.com/resource/word/image/G4S1U1_often.png",
	"4182_ping-pong":                  "http://reading-cdn.dubaner.com/resource/word/image/G4S1U1_ping-pong.png",
	"4183_friend":                     "http://reading-cdn.dubaner.com/resource/word/image/G4S1U1_friend.png",
	"4184_basketball":                 "http://reading-cdn.dubaner.com/resource/word/image/G4S1U1_basketball.png",
	"4185_be good at":                 "http://reading-cdn.dubaner.com/resource/word/image/G4S1U1_be_good_at.png",
	"4186_get up":                     "http://reading-cdn.dubaner.com/resource/word/image/G4S1U1_get_up.png",
	"4187_roller skating":             "http://reading-cdn.dubaner.com/resource/word/image/G4S1U1_roller_skating.png",
	"4188_running":                    "http://reading-cdn.dubaner.com/resource/word/image/G4S1U1_running.png",
	"4189_What about":                 "http://reading-cdn.dubaner.com/resource/word/image/G4S1U1_What_about.png",
	"4190_interesting":                "http://reading-cdn.dubaner.com/resource/word/image/G4S1U1_interesting.png",
	"4191_jumping rope":               "http://reading-cdn.dubaner.com/resource/word/image/G4S1U1_jumping_rope.png",
	"4192_late":                       "http://reading-cdn.dubaner.com/resource/word/image/G4S1U1_late.png",
	"4193_swim":                       "http://reading-cdn.dubaner.com/resource/word/image/G4S1U1_swim.png",
	"4194_on the weekend":             "http://reading-cdn.dubaner.com/resource/word/image/G4S1U2_on_the_weekend.png",
	"4195_paint":                      "http://reading-cdn.dubaner.com/resource/word/image/G4S1U2_paint.png",
	"4196_always":                     "http://reading-cdn.dubaner.com/resource/word/image/G4S1U2_always.png",
	"4197_pick fruit":                 "http://reading-cdn.dubaner.com/resource/word/image/G4S1U2_pick_fruit.png",
	"4198_play computer games":        "http://reading-cdn.dubaner.com/resource/word/image/G4S1U2_play_computer_games.png",
	"4199_visit one's grandparents":   "http://reading-cdn.dubaner.com/resource/word/image/G4S1U2_visit_one's_grandparents.png",
	"4200_fun":                        "http://reading-cdn.dubaner.com/resource/word/image/G4S1U2_fun.png",
	"4201_go fishing":                 "http://reading-cdn.dubaner.com/resource/word/image/G4S1U2_go_fishing.png",
	"4202_poor":                       "http://reading-cdn.dubaner.com/resource/word/image/G4S1U2_poor.png",
	"4203_go to a drawing club":       "http://reading-cdn.dubaner.com/resource/word/image/G4S1U2_go_to_a_drawing_club.png",
	"4204_go to the cinema":           "http://reading-cdn.dubaner.com/resource/word/image/G4S1U2_go_to_the_cinema.png",
	"4205_Saturday":                   "http://reading-cdn.dubaner.com/resource/word/image/G4S1U2_Saturday.png",
	"4206_hope":                       "http://reading-cdn.dubaner.com/resource/word/image/G4S1U2_hope.png",
	"4207_house":                      "http://reading-cdn.dubaner.com/resource/word/image/G4S1U2_house.png",
	"4208_so":                         "http://reading-cdn.dubaner.com/resource/word/image/G4S1U2_so.png",
	"4209_climb a hill":               "http://reading-cdn.dubaner.com/resource/word/image/G4S1U2_climb_a_hill.png",
	"4210_step":                       "http://reading-cdn.dubaner.com/resource/word/image/G4S1U2_step.png",
	"4211_day":                        "http://reading-cdn.dubaner.com/resource/word/image/G4S1U2_day.png",
	"4212_dirty":                      "http://reading-cdn.dubaner.com/resource/word/image/G4S1U2_dirty.png",
	"4213_evening":                    "http://reading-cdn.dubaner.com/resource/word/image/G4S1U2_evening.png",
	"4214_near":                       "http://reading-cdn.dubaner.com/resource/word/image/G4S1U2_near.png",
	"4215_their":                      "http://reading-cdn.dubaner.com/resource/word/image/G4S1U2_their.png",
	"4216_on foot":                    "http://reading-cdn.dubaner.com/resource/word/image/G4S1U3_on_foot.png",
	"4217_film":                       "http://reading-cdn.dubaner.com/resource/word/image/G4S1U3_film.png",
	"4218_transportation":             "http://reading-cdn.dubaner.com/resource/word/image/G4S1U3_transportation.png",
	"4219_park":                       "http://reading-cdn.dubaner.com/resource/word/image/G4S1U3_park.png",
	"4220_apple":                      "http://reading-cdn.dubaner.com/resource/word/image/G4S1U3_apple.png",
	"4221_usually":                    "http://reading-cdn.dubaner.com/resource/word/image/G4S1U3_usually.png",
	"4222_garden":                     "http://reading-cdn.dubaner.com/resource/word/image/G4S1U3_garden.png",
	"4223_gate":                       "http://reading-cdn.dubaner.com/resource/word/image/G4S1U3_gate.png",
	"4224_by bike":                    "http://reading-cdn.dubaner.com/resource/word/image/G4S1U3_by_bike.png",
	"4225_by boat":                    "http://reading-cdn.dubaner.com/resource/word/image/G4S1U3_by_boat.png",
	"4226_by bus":                     "http://reading-cdn.dubaner.com/resource/word/image/G4S1U3_by_bus.png",
	"4227_by car":                     "http://reading-cdn.dubaner.com/resource/word/image/G4S1U3_by_car.png",
	"4228_by plane":                   "http://reading-cdn.dubaner.com/resource/word/image/G4S1U3_by_plane.png",
	"4229_by school bus":              "http://reading-cdn.dubaner.com/resource/word/image/G4S1U3_by_school_bus.png",
	"4230_by ship":                    "http://reading-cdn.dubaner.com/resource/word/image/G4S1U3_by_ship.png",
	"4231_by subway":                  "http://reading-cdn.dubaner.com/resource/word/image/G4S1U3_by_subway.png",
	"4232_by taxi":                    "http://reading-cdn.dubaner.com/resource/word/image/G4S1U3_by_taxi.png",
	"4233_by train":                   "http://reading-cdn.dubaner.com/resource/word/image/G4S1U3_by_train.png",
	"4234_snow":                       "http://reading-cdn.dubaner.com/resource/word/image/G4S1U3_snow.png",
	"4235_come":                       "http://reading-cdn.dubaner.com/resource/word/image/G4S1U3_come.png",
	"4236_meeting place":              "http://reading-cdn.dubaner.com/resource/word/image/G4S1U3_meeting_place.png",
	"4237_earth":                      "http://reading-cdn.dubaner.com/resource/word/image/G4S1U3_earth.png",
	"4238_enjoy":                      "http://reading-cdn.dubaner.com/resource/word/image/G4S1U3_enjoy.png",
	"4239_theatre":                    "http://reading-cdn.dubaner.com/resource/word/image/G4S1U3_theatre.png",
	"4240_find":                       "http://reading-cdn.dubaner.com/resource/word/image/G4S1U4_find.png",
	"4241_paper":                      "http://reading-cdn.dubaner.com/resource/word/image/G4S1U4_paper.png",
	"4242_pen":                        "http://reading-cdn.dubaner.com/resource/word/image/G4S1U4_pen.png",
	"4243_pencil":                     "http://reading-cdn.dubaner.com/resource/word/image/G4S1U4_pencil.png",
	"4244_phone":                      "http://reading-cdn.dubaner.com/resource/word/image/G4S1U4_phone.png",
	"4245_use":                        "http://reading-cdn.dubaner.com/resource/word/image/G4S1U4_use.png",
	"4246_please":                     "http://reading-cdn.dubaner.com/resource/word/image/G4S1U4_please.png",
	"4247_glue stick":                 "http://reading-cdn.dubaner.com/resource/word/image/G4S1U4_glue_stick.png",
	"4248_ruler":                      "http://reading-cdn.dubaner.com/resource/word/image/G4S1U4_ruler.png",
	"4249_hamburger":                  "http://reading-cdn.dubaner.com/resource/word/image/G4S1U4_hamburger.png",
	"4250_schoolbag":                  "http://reading-cdn.dubaner.com/resource/word/image/G4S1U4_schoolbag.png",
	"4251_scissors":                   "http://reading-cdn.dubaner.com/resource/word/image/G4S1U4_scissors.png",
	"4252_shop":                       "http://reading-cdn.dubaner.com/resource/word/image/G4S1U4_shop.png",
	"4253_Information Centre":         "http://reading-cdn.dubaner.com/resource/word/image/G4S1U4_Information_Centre.png",
	"4254_knife":                      "http://reading-cdn.dubaner.com/resource/word/image/G4S1U4_knife.png",
	"4255_crayon":                     "http://reading-cdn.dubaner.com/resource/word/image/G4S1U4_crayon.png",
	"4256_dad":                        "http://reading-cdn.dubaner.com/resource/word/image/G4S1U4_dad.png",
	"4257_eraser":                     "http://reading-cdn.dubaner.com/resource/word/image/G4S1U4_eraser.png",
	"4258_Excuse me":                  "http://reading-cdn.dubaner.com/resource/word/image/G4S1U4_Excuse_me.png",
	"4259_play football":              "http://reading-cdn.dubaner.com/resource/word/image/G4S1U5_play_football.png",
	"4260_wait for":                   "http://reading-cdn.dubaner.com/resource/word/image/G4S1U5_wait_for.png",
	"4261_play with fire":             "http://reading-cdn.dubaner.com/resource/word/image/G4S1U5_play_with_fire.png",
	"4262_Be careful":                 "http://reading-cdn.dubaner.com/resource/word/image/G4S1U5_Be_careful.png",
	"4263_run down the stairs":        "http://reading-cdn.dubaner.com/resource/word/image/G4S1U5_run_down_the_stairs.png",
	"4264_green":                      "http://reading-cdn.dubaner.com/resource/word/image/G4S1U5_green.png",
	"4265_safe":                       "http://reading-cdn.dubaner.com/resource/word/image/G4S1U5_safe.png",
	"4266_safety rule":                "http://reading-cdn.dubaner.com/resource/word/image/G4S1U5_safety_rule.png",
	"4267_red":                        "http://reading-cdn.dubaner.com/resource/word/image/G4S1U5_red.png",
	"4268_sidewalk":                   "http://reading-cdn.dubaner.com/resource/word/image/G4S1U5_sidewalk.png",
	"4269_climb on the window ledge":  "http://reading-cdn.dubaner.com/resource/word/image/G4S1U5_climb_on_the_window_ledge.png",
	"4270_stop":                       "http://reading-cdn.dubaner.com/resource/word/image/G4S1U5_stop.png",
	"4271_street":                     "http://reading-cdn.dubaner.com/resource/word/image/G4S1U5_street.png",
	"4272_dangerous":                  "http://reading-cdn.dubaner.com/resource/word/image/G4S1U5_dangerous.png",
	"4273_Tuesday":                    "http://reading-cdn.dubaner.com/resource/word/image/G4S1U6_Tuesday.png",
	"4274_people":                     "http://reading-cdn.dubaner.com/resource/word/image/G4S1U6_people.png",
	"4275_Friday":                     "http://reading-cdn.dubaner.com/resource/word/image/G4S1U6_Friday.png",
	"4276_police officer":             "http://reading-cdn.dubaner.com/resource/word/image/G4S1U6_police_officer.png",
	"4277_Wednesday":                  "http://reading-cdn.dubaner.com/resource/word/image/G4S1U6_Wednesday.png",
	"4278_great":                      "http://reading-cdn.dubaner.com/resource/word/image/G4S1U6_great.png",
	"4279_worker":                     "http://reading-cdn.dubaner.com/resource/word/image/G4S1U6_worker.png",
	"4280_bus driver":                 "http://reading-cdn.dubaner.com/resource/word/image/G4S1U6_bus_driver.png",
	"4281_sick":                       "http://reading-cdn.dubaner.com/resource/word/image/G4S1U6_sick.png",
	"4282_in the future":              "http://reading-cdn.dubaner.com/resource/word/image/G4S1U6_in_the_future.png",
	"4283_job":                        "http://reading-cdn.dubaner.com/resource/word/image/G4S1U6_job.png",
	"4284_just":                       "http://reading-cdn.dubaner.com/resource/word/image/G4S1U6_just.png",
	"4285_sound":                      "http://reading-cdn.dubaner.com/resource/word/image/G4S1U6_sound.png",
	"4286_cook":                       "http://reading-cdn.dubaner.com/resource/word/image/G4S1U6_cook.png",
	"4287_doctor":                     "http://reading-cdn.dubaner.com/resource/word/image/G4S1U6_doctor.png",
	"4288_teach":                      "http://reading-cdn.dubaner.com/resource/word/image/G4S1U6_teach.png",
	"4289_teacher":                    "http://reading-cdn.dubaner.com/resource/word/image/G4S1U6_teacher.png",
	"4290_Monday":                     "http://reading-cdn.dubaner.com/resource/word/image/G4S1U6_Monday.png",
	"4291_myself":                     "http://reading-cdn.dubaner.com/resource/word/image/G4S1U6_myself.png",
	"4292_Thursday":                   "http://reading-cdn.dubaner.com/resource/word/image/G4S1U6_Thursday.png",
	"4293_farmer":                     "http://reading-cdn.dubaner.com/resource/word/image/G4S1U6_farmer.png",
	"4294_nurse":                      "http://reading-cdn.dubaner.com/resource/word/image/G4S1U6_nurse.png",
	"4295_across from":                "http://reading-cdn.dubaner.com/resource/word/image/G4S2U1_across_from.png",
	"4296_toy":                        "http://reading-cdn.dubaner.com/resource/word/image/G4S2U1_toy.png",
	"4297_turn left":                  "http://reading-cdn.dubaner.com/resource/word/image/G4S2U1_turn_left.png",
	"4298_turn right":                 "http://reading-cdn.dubaner.com/resource/word/image/G4S2U1_turn_right.png",
	"4299_ball":                       "http://reading-cdn.dubaner.com/resource/word/image/G4S2U1_ball.png",
	"4300_bank":                       "http://reading-cdn.dubaner.com/resource/word/image/G4S2U1_bank.png",
	"4301_get":                        "http://reading-cdn.dubaner.com/resource/word/image/G4S2U1_get.png",
	"4302_get to":                     "http://reading-cdn.dubaner.com/resource/word/image/G4S2U1_get_to.png",
	"4303_before":                     "http://reading-cdn.dubaner.com/resource/word/image/G4S2U1_before.png",
	"4304_post office":                "http://reading-cdn.dubaner.com/resource/word/image/G4S2U1_post_office.png",
	"4305_go straight":                "http://reading-cdn.dubaner.com/resource/word/image/G4S2U1_go_straight.png",
	"4306_between":                    "http://reading-cdn.dubaner.com/resource/word/image/G4S2U1_between.png",
	"4307_grocery":                    "http://reading-cdn.dubaner.com/resource/word/image/G4S2U1_grocery.png",
	"4308_bookshop":                   "http://reading-cdn.dubaner.com/resource/word/image/G4S2U1_bookshop.png",
	"4309_restaurant":                 "http://reading-cdn.dubaner.com/resource/word/image/G4S2U1_restaurant.png",
	"4310_school":                     "http://reading-cdn.dubaner.com/resource/word/image/G4S2U1_school.png",
	"4311_send":                       "http://reading-cdn.dubaner.com/resource/word/image/G4S2U1_send.png",
	"4312_hospital":                   "http://reading-cdn.dubaner.com/resource/word/image/G4S2U1_hospital.png",
	"4313_leave":                      "http://reading-cdn.dubaner.com/resource/word/image/G4S2U1_leave.png",
	"4314_crossroads":                 "http://reading-cdn.dubaner.com/resource/word/image/G4S2U1_crossroads.png",
	"4315_supermarket":                "http://reading-cdn.dubaner.com/resource/word/image/G4S2U1_supermarket.png",
	"4316_money":                      "http://reading-cdn.dubaner.com/resource/word/image/G4S2U1_money.png",
	"4317_neighbourhood":              "http://reading-cdn.dubaner.com/resource/word/image/G4S2U1_neighbourhood.png",
	"4318_next to":                    "http://reading-cdn.dubaner.com/resource/word/image/G4S2U1_next_to.png",
	"4319_place":                      "http://reading-cdn.dubaner.com/resource/word/image/G4S2U2_place.png",
	"4320_go boating":                 "http://reading-cdn.dubaner.com/resource/word/image/G4S2U2_go_boating.png",
	"4321_busy":                       "http://reading-cdn.dubaner.com/resource/word/image/G4S2U2_busy.png",
	"4322_see a film":                 "http://reading-cdn.dubaner.com/resource/word/image/G4S2U2_see_a_film.png",
	"4323_buy toys":                   "http://reading-cdn.dubaner.com/resource/word/image/G4S2U2_buy_toys.png",
	"4324_hotel":                      "http://reading-cdn.dubaner.com/resource/word/image/G4S2U2_hotel.png",
	"4325_central":                    "http://reading-cdn.dubaner.com/resource/word/image/G4S2U2_central.png",
	"4326_city":                       "http://reading-cdn.dubaner.com/resource/word/image/G4S2U2_city.png",
	"4327_king":                       "http://reading-cdn.dubaner.com/resource/word/image/G4S2U2_king.png",
	"4328_sport centre":               "http://reading-cdn.dubaner.com/resource/word/image/G4S2U2_sport_centre.png",
	"4329_square":                     "http://reading-cdn.dubaner.com/resource/word/image/G4S2U2_square.png",
	"4330_star":                       "http://reading-cdn.dubaner.com/resource/word/image/G4S2U2_star.png",
	"4331_station":                    "http://reading-cdn.dubaner.com/resource/word/image/G4S2U2_station.png",
	"4332_stay":                       "http://reading-cdn.dubaner.com/resource/word/image/G4S2U2_stay.png",
	"4333_street":                     "http://reading-cdn.dubaner.com/resource/word/image/G4S2U2_street.png",
	"4334_take photos":                "http://reading-cdn.dubaner.com/resource/word/image/G4S2U2_take_photos.png",
	"4335_dream":                      "http://reading-cdn.dubaner.com/resource/word/image/G4S2U2_dream.png",
	"4336_museum":                     "http://reading-cdn.dubaner.com/resource/word/image/G4S2U2_museum.png",
	"4337_thing":                      "http://reading-cdn.dubaner.com/resource/word/image/G4S2U2_thing.png",
	"4338_travel":                     "http://reading-cdn.dubaner.com/resource/word/image/G4S2U3_travel.png",
	"4339_visit the Mogon Caves":      "http://reading-cdn.dubaner.com/resource/word/image/G4S2U3_visit_the_Mogon_Caves.png",
	"4340_row a boat":                 "http://reading-cdn.dubaner.com/resource/word/image/G4S2U3_row_a_boat.png",
	"4341_West Lake":                  "http://reading-cdn.dubaner.com/resource/word/image/G4S2U3_West_Lake.png",
	"4342_sea":                        "http://reading-cdn.dubaner.com/resource/word/image/G4S2U3_sea.png",
	"4343_ski":                        "http://reading-cdn.dubaner.com/resource/word/image/G4S2U3_ski.png",
	"4344_summer vacation":            "http://reading-cdn.dubaner.com/resource/word/image/G4S2U3_summer_vacation.png",
	"4345_take photos":                "http://reading-cdn.dubaner.com/resource/word/image/G4S2U3_take_photos.png",
	"4346_the Great Wall":             "http://reading-cdn.dubaner.com/resource/word/image/G4S2U3_the_Great_Wall.png",
	"4347_eat seafood":                "http://reading-cdn.dubaner.com/resource/word/image/G4S2U3_eat_seafood.png",
	"4348_reading":                    "http://reading-cdn.dubaner.com/resource/word/image/G4S2U4_reading.png",
	"4349_hobby":                      "http://reading-cdn.dubaner.com/resource/word/image/G4S2U4_hobby.png",
	"4350_singing":                    "http://reading-cdn.dubaner.com/resource/word/image/G4S2U4_singing.png",
	"4351_catch":                      "http://reading-cdn.dubaner.com/resource/word/image/G4S2U4_catch.png",
	"4352_skateboarding":              "http://reading-cdn.dubaner.com/resource/word/image/G4S2U4_skateboarding.png",
	"4353_collecting erasers":         "http://reading-cdn.dubaner.com/resource/word/image/G4S2U4_collecting_erasers.png",
	"4354_stamp":                      "http://reading-cdn.dubaner.com/resource/word/image/G4S2U4_stamp.png",
	"4355_dancing":                    "http://reading-cdn.dubaner.com/resource/word/image/G4S2U4_dancing.png",
	"4356_different":                  "http://reading-cdn.dubaner.com/resource/word/image/G4S2U4_different.png",
	"4357_making models":              "http://reading-cdn.dubaner.com/resource/word/image/G4S2U4_making_models.png",
	"4358_doing jigsaw puzzles":       "http://reading-cdn.dubaner.com/resource/word/image/G4S2U4_doing_jigsaw_puzzles.png",
	"4359_once a week":                "http://reading-cdn.dubaner.com/resource/word/image/G4S2U5_once_a_week.png",
	"4360_twice a week":               "http://reading-cdn.dubaner.com/resource/word/image/G4S2U5_twice_a_week.png",
	"4361_free":                       "http://reading-cdn.dubaner.com/resource/word/image/G4S2U5_free.png",
	"4362_play the violin":            "http://reading-cdn.dubaner.com/resource/word/image/G4S2U5_play_the_violin.png",
	"4363_go camping":                 "http://reading-cdn.dubaner.com/resource/word/image/G4S2U5_go_camping.png",
	"4364_go for a picnic":            "http://reading-cdn.dubaner.com/resource/word/image/G4S2U5_go_for_a_picnic.png",
	"4365_go skating":                 "http://reading-cdn.dubaner.com/resource/word/image/G4S2U5_go_skating.png",
	"4366_do the housework":           "http://reading-cdn.dubaner.com/resource/word/image/G4S2U5_do_the_housework.png",
	"4367_never":                      "http://reading-cdn.dubaner.com/resource/word/image/G4S2U5_never.png",
	"4368_three times a week":         "http://reading-cdn.dubaner.com/resource/word/image/G4S2U5_three_times_a_week.png",
	"4369_Australia":                  "http://reading-cdn.dubaner.com/resource/word/image/G4S2U6_Australia.png",
	"4370_pretty":                     "http://reading-cdn.dubaner.com/resource/word/image/G4S2U6_pretty.png",
	"4371_Big Ben":                    "http://reading-cdn.dubaner.com/resource/word/image/G4S2U6_Big_Ben.png",
	"4372_campfire":                   "http://reading-cdn.dubaner.com/resource/word/image/G4S2U6_campfire.png",
	"4373_Canada":                     "http://reading-cdn.dubaner.com/resource/word/image/G4S2U6_Canada.png",
	"4374_China":                      "http://reading-cdn.dubaner.com/resource/word/image/G4S2U6_China.png",
	"4375_koala":                      "http://reading-cdn.dubaner.com/resource/word/image/G4S2U6_koala.png",
	"4376_country":                    "http://reading-cdn.dubaner.com/resource/word/image/G4S2U6_country.png",
	"4377_cute":                       "http://reading-cdn.dubaner.com/resource/word/image/G4S2U6_cute.png",
	"4378_Disneyland":                 "http://reading-cdn.dubaner.com/resource/word/image/G4S2U6_Disneyland.png",
	"4379_maple leaves":               "http://reading-cdn.dubaner.com/resource/word/image/G4S2U6_maple_leaves.png",
	"4380_the UK":                     "http://reading-cdn.dubaner.com/resource/word/image/G4S2U6_the_UK.png",
	"4381_the USA":                    "http://reading-cdn.dubaner.com/resource/word/image/G4S2U6_the_USA.png",
	"4382_active":                     "http://reading-cdn.dubaner.com/resource/word/image/G5S1U1_active.png",
	"4383_all":                        "http://reading-cdn.dubaner.com/resource/word/image/G5S1U1_all.png",
	"4384_party":                      "http://reading-cdn.dubaner.com/resource/word/image/G5S1U1_party.png",
	"4385_forget":                     "http://reading-cdn.dubaner.com/resource/word/image/G5S1U1_forget.png",
	"4386_friendly":                   "http://reading-cdn.dubaner.com/resource/word/image/G5S1U1_friendly.png",
	"4387_bark":                       "http://reading-cdn.dubaner.com/resource/word/image/G5S1U1_bark.png",
	"4388_polite":                     "http://reading-cdn.dubaner.com/resource/word/image/G5S1U1_polite.png",
	"4389_popular":                    "http://reading-cdn.dubaner.com/resource/word/image/G5S1U1_popular.png",
	"4390_quiet":                      "http://reading-cdn.dubaner.com/resource/word/image/G5S1U1_quiet.png",
	"4391_with":                       "http://reading-cdn.dubaner.com/resource/word/image/G5S1U1_with.png",
	"4392_but":                        "http://reading-cdn.dubaner.com/resource/word/image/G5S1U1_but.png",
	"4393_helpful":                    "http://reading-cdn.dubaner.com/resource/word/image/G5S1U1_helpful.png",
	"4394_careless":                   "http://reading-cdn.dubaner.com/resource/word/image/G5S1U1_careless.png",
	"4395_sometimes":                  "http://reading-cdn.dubaner.com/resource/word/image/G5S1U1_sometimes.png",
	"4396_clever":                     "http://reading-cdn.dubaner.com/resource/word/image/G5S1U1_clever.png",
	"4397_cute":                       "http://reading-cdn.dubaner.com/resource/word/image/G5S1U1_cute.png",
	"4398_talk":                       "http://reading-cdn.dubaner.com/resource/word/image/G5S1U1_talk.png",
	"4399_wear glasses":               "http://reading-cdn.dubaner.com/resource/word/image/G5S1U2_wear_glasses.png",
	"4400_guess":                      "http://reading-cdn.dubaner.com/resource/word/image/G5S1U2_guess.png",
	"4401_has":                        "http://reading-cdn.dubaner.com/resource/word/image/G5S1U2_has.png",
	"4402_young":                      "http://reading-cdn.dubaner.com/resource/word/image/G5S1U2_young.png",
	"4403_slim":                       "http://reading-cdn.dubaner.com/resource/word/image/G5S1U2_slim.png",
	"4404_curly":                      "http://reading-cdn.dubaner.com/resource/word/image/G5S1U2_curly.png",
	"4405_straight":                   "http://reading-cdn.dubaner.com/resource/word/image/G5S1U2_straight.png",
	"4406_teach":                      "http://reading-cdn.dubaner.com/resource/word/image/G5S1U2_teach.png",
	"4407_nice":                       "http://reading-cdn.dubaner.com/resource/word/image/G5S1U2_nice.png",
	"4408_panda":                      "http://reading-cdn.dubaner.com/resource/word/image/G5S1U3_panda.png",
	"4409_animal":                     "http://reading-cdn.dubaner.com/resource/word/image/G5S1U3_animal.png",
	"4410_pig":                        "http://reading-cdn.dubaner.com/resource/word/image/G5S1U3_pig.png",
	"4411_bee":                        "http://reading-cdn.dubaner.com/resource/word/image/G5S1U3_bee.png",
	"4412_why":                        "http://reading-cdn.dubaner.com/resource/word/image/G5S1U3_why.png",
	"4413_butterfly":                  "http://reading-cdn.dubaner.com/resource/word/image/G5S1U3_butterfly.png",
	"4414_sheep":                      "http://reading-cdn.dubaner.com/resource/word/image/G5S1U3_sheep.png",
	"4415_horse":                      "http://reading-cdn.dubaner.com/resource/word/image/G5S1U3_horse.png",
	"4416_cow":                        "http://reading-cdn.dubaner.com/resource/word/image/G5S1U3_cow.png",
	"4417_lovely":                     "http://reading-cdn.dubaner.com/resource/word/image/G5S1U3_lovely.png",
	"4418_elephant":                   "http://reading-cdn.dubaner.com/resource/word/image/G5S1U3_elephant.png",
	"4419_farm":                       "http://reading-cdn.dubaner.com/resource/word/image/G5S1U3_farm.png",
	"4420_fast":                       "http://reading-cdn.dubaner.com/resource/word/image/G5S1U3_fast.png",
	"4421_a box of crayons":           "http://reading-cdn.dubaner.com/resource/word/image/G5S1U4_a_box_of_crayons.png",
	"4422_a lot":                      "http://reading-cdn.dubaner.com/resource/word/image/G5S1U4_a_lot.png",
	"4423_a pair of scissors":         "http://reading-cdn.dubaner.com/resource/word/image/G5S1U4_a_pair_of_scissors.png",
	"4424_only":                       "http://reading-cdn.dubaner.com/resource/word/image/G5S1U4_only.png",
	"4425_also":                       "http://reading-cdn.dubaner.com/resource/word/image/G5S1U4_also.png",
	"4426_pencil box":                 "http://reading-cdn.dubaner.com/resource/word/image/G5S1U4_pencil_box.png",
	"4427_pencil sharpener":           "http://reading-cdn.dubaner.com/resource/word/image/G5S1U4_pencil_sharpener.png",
	"4428_please":                     "http://reading-cdn.dubaner.com/resource/word/image/G5S1U4_please.png",
	"4429_great":                      "http://reading-cdn.dubaner.com/resource/word/image/G5S1U4_great.png",
	"4430_saleswoman":                 "http://reading-cdn.dubaner.com/resource/word/image/G5S1U4_saleswoman.png",
	"4431_how much":                   "http://reading-cdn.dubaner.com/resource/word/image/G5S1U4_how_much.png",
	"4432_love":                       "http://reading-cdn.dubaner.com/resource/word/image/G5S1U4_love.png",
	"4433_exercise book":              "http://reading-cdn.dubaner.com/resource/word/image/G5S1U4_exercise_book.png",
	"4434_wonderful":                  "http://reading-cdn.dubaner.com/resource/word/image/G5S1U5_wonderful.png",
	"4435_cartoons":                   "http://reading-cdn.dubaner.com/resource/word/image/G5S1U5_cartoons.png",
	"4436_cool":                       "http://reading-cdn.dubaner.com/resource/word/image/G5S1U5_cool.png",
	"4437_nature shows":               "http://reading-cdn.dubaner.com/resource/word/image/G5S1U5_nature_shows.png",
	"4438_news shows":                 "http://reading-cdn.dubaner.com/resource/word/image/G5S1U5_news_shows.png",
	"4439_fantastic":                  "http://reading-cdn.dubaner.com/resource/word/image/G5S1U5_fantastic.png",
	"4440_wash clothes":               "http://reading-cdn.dubaner.com/resource/word/image/G5S1U6_wash_clothes.png",
	"4441_call":                       "http://reading-cdn.dubaner.com/resource/word/image/G5S1U6_call.png",
	"4442_chore":                      "http://reading-cdn.dubaner.com/resource/word/image/G5S1U6_chore.png",
	"4443_clean the room":             "http://reading-cdn.dubaner.com/resource/word/image/G5S1U6_clean_the_room.png",
	"4444_make the bed":               "http://reading-cdn.dubaner.com/resource/word/image/G5S1U6_make_the_bed.png",
	"4445_sweep the floor":            "http://reading-cdn.dubaner.com/resource/word/image/G5S1U6_sweep_the_floor.png",
	"4446_take out the rubbish":       "http://reading-cdn.dubaner.com/resource/word/image/G5S1U6_take_out_the_rubbish.png",
	"4447_tidy the desk":              "http://reading-cdn.dubaner.com/resource/word/image/G5S1U6_tidy_the_desk.png",
	"4448_a lot of":                   "http://reading-cdn.dubaner.com/resource/word/image/G5S2U1_a_lot_of.png",
	"4449_too much":                   "http://reading-cdn.dubaner.com/resource/word/image/G5S2U1_too_much.png",
	"4450_advice":                     "http://reading-cdn.dubaner.com/resource/word/image/G5S2U1_advice.png",
	"4451_toothache":                  "http://reading-cdn.dubaner.com/resource/word/image/G5S2U1_toothache.png",
	"4452_always":                     "http://reading-cdn.dubaner.com/resource/word/image/G5S2U1_always.png",
	"4453_before":                     "http://reading-cdn.dubaner.com/resource/word/image/G5S2U1_before.png",
	"4454_go to bed":                  "http://reading-cdn.dubaner.com/resource/word/image/G5S2U1_go_to_bed.png",
	"4455_headache":                   "http://reading-cdn.dubaner.com/resource/word/image/G5S2U1_headache.png",
	"4456_candy":                      "http://reading-cdn.dubaner.com/resource/word/image/G5S2U1_candy.png",
	"4457_sleepy":                     "http://reading-cdn.dubaner.com/resource/word/image/G5S2U1_sleepy.png",
	"4458_stomachache":                "http://reading-cdn.dubaner.com/resource/word/image/G5S2U1_stomachache.png",
	"4459_subject":                    "http://reading-cdn.dubaner.com/resource/word/image/G5S2U1_subject.png",
	"4460_dirty":                      "http://reading-cdn.dubaner.com/resource/word/image/G5S2U1_dirty.png",
	"4461_mark":                       "http://reading-cdn.dubaner.com/resource/word/image/G5S2U1_mark.png",
	"4462_drink":                      "http://reading-cdn.dubaner.com/resource/word/image/G5S2U1_drink.png",
	"4463_more":                       "http://reading-cdn.dubaner.com/resource/word/image/G5S2U1_more.png",
	"4464_early":                      "http://reading-cdn.dubaner.com/resource/word/image/G5S2U1_early.png",
	"4465_exercise":                   "http://reading-cdn.dubaner.com/resource/word/image/G5S2U1_exercise.png",
	"4466_tired":                      "http://reading-cdn.dubaner.com/resource/word/image/G5S2U1_tired.png",
	"4467_office":                     "http://reading-cdn.dubaner.com/resource/word/image/G5S2U2_office.png",
	"4468_together":                   "http://reading-cdn.dubaner.com/resource/word/image/G5S2U2_together.png",
	"4469_Father's Day":               "http://reading-cdn.dubaner.com/resource/word/image/G5S2U2_Father's_Day.png",
	"4470_fifth(5th)":                 "http://reading-cdn.dubaner.com/resource/word/image/G5S2U2_fifth(5th).png",
	"4471_Tree Planting Day":          "http://reading-cdn.dubaner.com/resource/word/image/G5S2U2_Tree_Planting_Day.png",
	"4472_twelfth(12th)":              "http://reading-cdn.dubaner.com/resource/word/image/G5S2U2_twelfth(12th).png",
	"4473_twenty-fifth(25th)":         "http://reading-cdn.dubaner.com/resource/word/image/G5S2U2_twenty-fifth(25th).png",
	"4474_plant":                      "http://reading-cdn.dubaner.com/resource/word/image/G5S2U2_plant.png",
	"4475_birthday":                   "http://reading-cdn.dubaner.com/resource/word/image/G5S2U2_birthday.png",
	"4476_have a picnic":              "http://reading-cdn.dubaner.com/resource/word/image/G5S2U2_have_a_picnic.png",
	"4477_Teacher's Day":              "http://reading-cdn.dubaner.com/resource/word/image/G5S2U2_Teacher's_Day.png",
	"4478_celebrate":                  "http://reading-cdn.dubaner.com/resource/word/image/G5S2U2_celebrate.png",
	"4479_children's Day":             "http://reading-cdn.dubaner.com/resource/word/image/G5S2U2_children's_Day.png",
	"4480_Christmas Day":              "http://reading-cdn.dubaner.com/resource/word/image/G5S2U2_Christmas_Day.png",
	"4481_special":                    "http://reading-cdn.dubaner.com/resource/word/image/G5S2U2_special.png",
	"4482_make a poster":              "http://reading-cdn.dubaner.com/resource/word/image/G5S2U2_make_a_poster.png",
	"4483_tenth(10th)":                "http://reading-cdn.dubaner.com/resource/word/image/G5S2U2_tenth(10th).png",
	"4484_Mother's Day":               "http://reading-cdn.dubaner.com/resource/word/image/G5S2U2_Mother's_Day.png",
	"4485_National Day":               "http://reading-cdn.dubaner.com/resource/word/image/G5S2U2_National_Day.png",
	"4486_New Year's Day":             "http://reading-cdn.dubaner.com/resource/word/image/G5S2U2_New_Year's_Day.png",
	"4487_flower show":                "http://reading-cdn.dubaner.com/resource/word/image/G5S2U3_flower_show.png",
	"4488_say":                        "http://reading-cdn.dubaner.com/resource/word/image/G5S2U3_say.png",
	"4489_write a letter":             "http://reading-cdn.dubaner.com/resource/word/image/G5S2U3_write_a_letter.png",
	"4490_send a short message":       "http://reading-cdn.dubaner.com/resource/word/image/G5S2U3_send_a_short_message.png",
	"4491_send an email":              "http://reading-cdn.dubaner.com/resource/word/image/G5S2U3_send_an_email.png",
	"4492_mail a present":             "http://reading-cdn.dubaner.com/resource/word/image/G5S2U3_mail_a_present.png",
	"4493_make a card":                "http://reading-cdn.dubaner.com/resource/word/image/G5S2U3_make_a_card.png",
	"4494_make a phone call":          "http://reading-cdn.dubaner.com/resource/word/image/G5S2U3_make_a_phone_call.png",
	"4495_make a video call":          "http://reading-cdn.dubaner.com/resource/word/image/G5S2U3_make_a_video_call.png",
	"4496_everywhere":                 "http://reading-cdn.dubaner.com/resource/word/image/G5S2U3_everywhere.png",
	"4497_badminton":                  "http://reading-cdn.dubaner.com/resource/word/image/G5S2U4_badminton.png",
	"4498_visited grandparents":       "http://reading-cdn.dubaner.com/resource/word/image/G5S2U4_visited_grandparents.png",
	"4499_played chess":               "http://reading-cdn.dubaner.com/resource/word/image/G5S2U4_played_chess.png",
	"4500_played computer games":      "http://reading-cdn.dubaner.com/resource/word/image/G5S2U4_played_computer_games.png",
	"4501_played the piano":           "http://reading-cdn.dubaner.com/resource/word/image/G5S2U4_played_the_piano.png",
	"4502_washed clothes":             "http://reading-cdn.dubaner.com/resource/word/image/G5S2U4_washed_clothes.png",
	"4503_watched TV":                 "http://reading-cdn.dubaner.com/resource/word/image/G5S2U4_watched_TV.png",
	"4504_rowed a boat":               "http://reading-cdn.dubaner.com/resource/word/image/G5S2U4_rowed_a_boat.png",
	"4505_boring":                     "http://reading-cdn.dubaner.com/resource/word/image/G5S2U4_boring.png",
	"4506_won":                        "http://reading-cdn.dubaner.com/resource/word/image/G5S2U4_won.png",
	"4507_jumped rope":                "http://reading-cdn.dubaner.com/resource/word/image/G5S2U4_jumped_rope.png",
	"4508_cleaned the window":         "http://reading-cdn.dubaner.com/resource/word/image/G5S2U4_cleaned_the_window.png",
	"4509_climbed a hill":             "http://reading-cdn.dubaner.com/resource/word/image/G5S2U4_climbed_a_hill.png",
	"4510_stayed at home":             "http://reading-cdn.dubaner.com/resource/word/image/G5S2U4_stayed_at_home.png",
	"4511_listened to music":          "http://reading-cdn.dubaner.com/resource/word/image/G5S2U4_listened_to_music.png",
	"4512_danced":                     "http://reading-cdn.dubaner.com/resource/word/image/G5S2U4_danced.png",
	"4513_felt happy":                 "http://reading-cdn.dubaner.com/resource/word/image/G5S2U5_felt_happy.png",
	"4514_took photos":                "http://reading-cdn.dubaner.com/resource/word/image/G5S2U5_took_photos.png",
	"4515_ate ice-cream":              "http://reading-cdn.dubaner.com/resource/word/image/G5S2U5_ate_ice-cream.png",
	"4516_French fries":               "http://reading-cdn.dubaner.com/resource/word/image/G5S2U5_French_fries.png",
	"4517_went to the beach":          "http://reading-cdn.dubaner.com/resource/word/image/G5S2U5_went_to_the_beach.png",
	"4518_were":                       "http://reading-cdn.dubaner.com/resource/word/image/G5S2U5_were.png",
	"4519_sad":                        "http://reading-cdn.dubaner.com/resource/word/image/G5S2U5_sad.png",
	"4520_saw flowers":                "http://reading-cdn.dubaner.com/resource/word/image/G5S2U5_saw_flowers.png",
	"4521_bought some gifts":          "http://reading-cdn.dubaner.com/resource/word/image/G5S2U5_bought_some_gifts.png",
	"4522_slept":                      "http://reading-cdn.dubaner.com/resource/word/image/G5S2U5_slept.png",
	"4523_left":                       "http://reading-cdn.dubaner.com/resource/word/image/G5S2U5_left.png",
	"4524_delicious":                  "http://reading-cdn.dubaner.com/resource/word/image/G5S2U5_delicious.png",
	"4525_swam":                       "http://reading-cdn.dubaner.com/resource/word/image/G5S2U5_swam.png",
	"4526_drank cold drinks":          "http://reading-cdn.dubaner.com/resource/word/image/G5S2U5_drank_cold_drinks.png",
	"4527_the Stone Forest":           "http://reading-cdn.dubaner.com/resource/word/image/G5S2U5_the_Stone_Forest.png",
	"4528_fifteenth(15th)":            "http://reading-cdn.dubaner.com/resource/word/image/G5S2U6_fifteenth(15th).png",
	"4529_out of":                     "http://reading-cdn.dubaner.com/resource/word/image/G5S2U6_out_of.png",
	"4530_all over":                   "http://reading-cdn.dubaner.com/resource/word/image/G5S2U6_all_over.png",
	"4531_was born":                   "http://reading-cdn.dubaner.com/resource/word/image/G5S2U6_was_born.png",
	"4532_went to kindergarten":       "http://reading-cdn.dubaner.com/resource/word/image/G5S2U6_went_to_kindergarten.png",
	"4533_went to school":             "http://reading-cdn.dubaner.com/resource/word/image/G5S2U6_went_to_school.png",
	"4534_wet":                        "http://reading-cdn.dubaner.com/resource/word/image/G5S2U6_wet.png",
	"4535_into":                       "http://reading-cdn.dubaner.com/resource/word/image/G5S2U6_into.png",
	"4536_chopsticks":                 "http://reading-cdn.dubaner.com/resource/word/image/G5S2U6_chopsticks.png",
	"4537_learned to ride a bike":     "http://reading-cdn.dubaner.com/resource/word/image/G5S2U6_learned_to_ride_a_bike.png",
	"4538_learned to swim":            "http://reading-cdn.dubaner.com/resource/word/image/G5S2U6_learned_to_swim.png",
	"4539_learned to walk":            "http://reading-cdn.dubaner.com/resource/word/image/G5S2U6_learned_to_walk.png",
	"4540_started to buy things":      "http://reading-cdn.dubaner.com/resource/word/image/G5S2U6_started_to_buy_things.png",
	"4541_started to speak":           "http://reading-cdn.dubaner.com/resource/word/image/G5S2U6_started_to_speak.png",
	"4542_started to study English":   "http://reading-cdn.dubaner.com/resource/word/image/G5S2U6_started_to_study_English.png",
	"4543_started to use a computer":  "http://reading-cdn.dubaner.com/resource/word/image/G5S2U6_started_to_use_a_computer.png",
	"4544_foggy":                      "http://reading-cdn.dubaner.com/resource/word/image/G6S1U1_foggy.png",
	"4545_around":                     "http://reading-cdn.dubaner.com/resource/word/image/G6S1U1_around.png",
	"4546_forest":                     "http://reading-cdn.dubaner.com/resource/word/image/G6S1U1_forest.png",
	"4547_vacation":                   "http://reading-cdn.dubaner.com/resource/word/image/G6S1U1_vacation.png",
	"4548_garden":                     "http://reading-cdn.dubaner.com/resource/word/image/G6S1U1_garden.png",
	"4549_west":                       "http://reading-cdn.dubaner.com/resource/word/image/G6S1U1_west.png",
	"4550_silk":                       "http://reading-cdn.dubaner.com/resource/word/image/G6S1U1_silk.png",
	"4551_soup":                       "http://reading-cdn.dubaner.com/resource/word/image/G6S1U1_soup.png",
	"4552_south":                      "http://reading-cdn.dubaner.com/resource/word/image/G6S1U1_south.png",
	"4553_spicy":                      "http://reading-cdn.dubaner.com/resource/word/image/G6S1U1_spicy.png",
	"4554_stone":                      "http://reading-cdn.dubaner.com/resource/word/image/G6S1U1_stone.png",
	"4555_map":                        "http://reading-cdn.dubaner.com/resource/word/image/G6S1U1_map.png",
	"4556_taste":                      "http://reading-cdn.dubaner.com/resource/word/image/G6S1U1_taste.png",
	"4557_temple":                     "http://reading-cdn.dubaner.com/resource/word/image/G6S1U1_temple.png",
	"4558_morning tea":                "http://reading-cdn.dubaner.com/resource/word/image/G6S1U1_morning_tea.png",
	"4559_east":                       "http://reading-cdn.dubaner.com/resource/word/image/G6S1U1_east.png",
	"4560_the Potala Palace":          "http://reading-cdn.dubaner.com/resource/word/image/G6S1U1_the_Potala_Palace.png",
	"4561_the Summer Palace":          "http://reading-cdn.dubaner.com/resource/word/image/G6S1U1_the_Summer_Palace.png",
	"4562_The Terracotta Army":        "http://reading-cdn.dubaner.com/resource/word/image/G6S1U1_The_Terracotta_Army.png",
	"4563_the Yangtze River":          "http://reading-cdn.dubaner.com/resource/word/image/G6S1U1_the_Yangtze_River.png",
	"4564_famous":                     "http://reading-cdn.dubaner.com/resource/word/image/G6S1U1_famous.png",
	"4565_north":                      "http://reading-cdn.dubaner.com/resource/word/image/G6S1U1_north.png",
	"4566_Toronto":                    "http://reading-cdn.dubaner.com/resource/word/image/G6S1U2_Toronto.png",
	"4567_Tower Bridge":               "http://reading-cdn.dubaner.com/resource/word/image/G6S1U2_Tower_Bridge.png",
	"4568_French":                     "http://reading-cdn.dubaner.com/resource/word/image/G6S1U2_French.png",
	"4569_Washington":                 "http://reading-cdn.dubaner.com/resource/word/image/G6S1U2_Washington.png",
	"4570_president":                  "http://reading-cdn.dubaner.com/resource/word/image/G6S1U2_president.png",
	"4571_hiking":                     "http://reading-cdn.dubaner.com/resource/word/image/G6S1U2_hiking.png",
	"4572_kangaroo":                   "http://reading-cdn.dubaner.com/resource/word/image/G6S1U2_kangaroo.png",
	"4573_speak":                      "http://reading-cdn.dubaner.com/resource/word/image/G6S1U2_speak.png",
	"4574_clock":                      "http://reading-cdn.dubaner.com/resource/word/image/G6S1U2_clock.png",
	"4575_London":                     "http://reading-cdn.dubaner.com/resource/word/image/G6S1U2_London.png",
	"4576_sunrise":                    "http://reading-cdn.dubaner.com/resource/word/image/G6S1U2_sunrise.png",
	"4577_Sydney":                     "http://reading-cdn.dubaner.com/resource/word/image/G6S1U2_Sydney.png",
	"4578_the British Museum":         "http://reading-cdn.dubaner.com/resource/word/image/G6S1U2_the_British_Museum.png",
	"4579_the CN Tower":               "http://reading-cdn.dubaner.com/resource/word/image/G6S1U2_the_CN_Tower.png",
	"4580_the London Eye":             "http://reading-cdn.dubaner.com/resource/word/image/G6S1U2_the_London_Eye.png",
	"4581_the Opera House":            "http://reading-cdn.dubaner.com/resource/word/image/G6S1U2_the_Opera_House.png",
	"4582_the White House":            "http://reading-cdn.dubaner.com/resource/word/image/G6S1U2_the_White_House.png",
	"4583_Africa":                     "http://reading-cdn.dubaner.com/resource/word/image/G6S1U3_Africa.png",
	"4584_trunk":                      "http://reading-cdn.dubaner.com/resource/word/image/G6S1U3_trunk.png",
	"4585_peanut":                     "http://reading-cdn.dubaner.com/resource/word/image/G6S1U3_peanut.png",
	"4586_tusk":                       "http://reading-cdn.dubaner.com/resource/word/image/G6S1U3_tusk.png",
	"4587_penguin":                    "http://reading-cdn.dubaner.com/resource/word/image/G6S1U3_penguin.png",
	"4588_Asia":                       "http://reading-cdn.dubaner.com/resource/word/image/G6S1U3_Asia.png",
	"4589_bird":                       "http://reading-cdn.dubaner.com/resource/word/image/G6S1U3_bird.png",
	"4590_whale":                      "http://reading-cdn.dubaner.com/resource/word/image/G6S1U3_whale.png",
	"4591_reptile":                    "http://reading-cdn.dubaner.com/resource/word/image/G6S1U3_reptile.png",
	"4592_shark":                      "http://reading-cdn.dubaner.com/resource/word/image/G6S1U3_shark.png",
	"4593_insect":                     "http://reading-cdn.dubaner.com/resource/word/image/G6S1U3_insect.png",
	"4594_smart":                      "http://reading-cdn.dubaner.com/resource/word/image/G6S1U3_smart.png",
	"4595_kind":                       "http://reading-cdn.dubaner.com/resource/word/image/G6S1U3_kind.png",
	"4596_spend":                      "http://reading-cdn.dubaner.com/resource/word/image/G6S1U3_spend.png",
	"4597_mammal":                     "http://reading-cdn.dubaner.com/resource/word/image/G6S1U3_mammal.png",
	"4598_metre":                      "http://reading-cdn.dubaner.com/resource/word/image/G6S1U3_metre.png",
	"4599_fan":                        "http://reading-cdn.dubaner.com/resource/word/image/G6S1U3_fan.png",
	"4600_find":                       "http://reading-cdn.dubaner.com/resource/word/image/G6S1U4_find.png",
	"4601_angry":                      "http://reading-cdn.dubaner.com/resource/word/image/G6S1U4_angry.png",
	"4602_because":                    "http://reading-cdn.dubaner.com/resource/word/image/G6S1U4_because.png",
	"4603_proud":                      "http://reading-cdn.dubaner.com/resource/word/image/G6S1U4_proud.png",
	"4604_race":                       "http://reading-cdn.dubaner.com/resource/word/image/G6S1U4_race.png",
	"4605_sad":                        "http://reading-cdn.dubaner.com/resource/word/image/G6S1U4_sad.png",
	"4606_win":                        "http://reading-cdn.dubaner.com/resource/word/image/G6S1U4_win.png",
	"4607_scared":                     "http://reading-cdn.dubaner.com/resource/word/image/G6S1U4_scared.png",
	"4608_happy":                      "http://reading-cdn.dubaner.com/resource/word/image/G6S1U4_happy.png",
	"4609_worried":                    "http://reading-cdn.dubaner.com/resource/word/image/G6S1U4_worried.png",
	"4610_hurt":                       "http://reading-cdn.dubaner.com/resource/word/image/G6S1U4_hurt.png",
	"4611_ill":                        "http://reading-cdn.dubaner.com/resource/word/image/G6S1U4_ill.png",
	"4612_competition":                "http://reading-cdn.dubaner.com/resource/word/image/G6S1U4_competition.png",
	"4613_cry":                        "http://reading-cdn.dubaner.com/resource/word/image/G6S1U4_cry.png",
	"4614_test":                       "http://reading-cdn.dubaner.com/resource/word/image/G6S1U4_test.png",
	"4615_excited":                    "http://reading-cdn.dubaner.com/resource/word/image/G6S1U4_excited.png",
	"4616_paint":                      "http://reading-cdn.dubaner.com/resource/word/image/G6S1U5_paint.png",
	"4617_American":                   "http://reading-cdn.dubaner.com/resource/word/image/G6S1U5_American.png",
	"4618_artist":                     "http://reading-cdn.dubaner.com/resource/word/image/G6S1U5_artist.png",
	"4619_French":                     "http://reading-cdn.dubaner.com/resource/word/image/G6S1U5_French.png",
	"4620_university":                 "http://reading-cdn.dubaner.com/resource/word/image/G6S1U5_university.png",
	"4621_poem":                       "http://reading-cdn.dubaner.com/resource/word/image/G6S1U5_poem.png",
	"4622_poet":                       "http://reading-cdn.dubaner.com/resource/word/image/G6S1U5_poet.png",
	"4623_blind":                      "http://reading-cdn.dubaner.com/resource/word/image/G6S1U5_blind.png",
	"4624_scientist":                  "http://reading-cdn.dubaner.com/resource/word/image/G6S1U5_scientist.png",
	"4625_writer":                     "http://reading-cdn.dubaner.com/resource/word/image/G6S1U5_writer.png",
	"4626_invent":                     "http://reading-cdn.dubaner.com/resource/word/image/G6S1U5_invent.png",
	"4627_invention":                  "http://reading-cdn.dubaner.com/resource/word/image/G6S1U5_invention.png",
	"4628_inventor":                   "http://reading-cdn.dubaner.com/resource/word/image/G6S1U5_inventor.png",
	"4629_story":                      "http://reading-cdn.dubaner.com/resource/word/image/G6S1U5_story.png",
	"4630_study":                      "http://reading-cdn.dubaner.com/resource/word/image/G6S1U5_study.png",
	"4631_Danish":                     "http://reading-cdn.dubaner.com/resource/word/image/G6S1U5_Danish.png",
	"4632_deaf":                       "http://reading-cdn.dubaner.com/resource/word/image/G6S1U5_deaf.png",
	"4633_fall":                       "http://reading-cdn.dubaner.com/resource/word/image/G6S1U5_fall.png",
	"4634_pen pal":                    "http://reading-cdn.dubaner.com/resource/word/image/G6S1U6_pen_pal.png",
	"4635_pity":                       "http://reading-cdn.dubaner.com/resource/word/image/G6S1U6_pity.png",
	"4636_be afraid of":               "http://reading-cdn.dubaner.com/resource/word/image/G6S1U6_be_afraid_of.png",
	"4637_prize":                      "http://reading-cdn.dubaner.com/resource/word/image/G6S1U6_prize.png",
	"4638_bring":                      "http://reading-cdn.dubaner.com/resource/word/image/G6S1U6_bring.png",
	"4639_broken":                     "http://reading-cdn.dubaner.com/resource/word/image/G6S1U6_broken.png",
	"4640_hear":                       "http://reading-cdn.dubaner.com/resource/word/image/G6S1U6_hear.png",
	"4641_ice lantern":                "http://reading-cdn.dubaner.com/resource/word/image/G6S1U6_ice_lantern.png",
	"4642_look forward to":            "http://reading-cdn.dubaner.com/resource/word/image/G6S1U6_look_forward_to.png",
	"4643_dumpling":                   "http://reading-cdn.dubaner.com/resource/word/image/G6S1U6_dumpling.png",
	"4644_fan":                        "http://reading-cdn.dubaner.com/resource/word/image/G6S1U6_fan.png",
	"4645_airport":                    "http://reading-cdn.dubaner.com/resource/word/image/G6S2U1_airport.png",
	"4646_arrive":                     "http://reading-cdn.dubaner.com/resource/word/image/G6S2U1_arrive.png",
	"4647_wardrobe":                   "http://reading-cdn.dubaner.com/resource/word/image/G6S2U1_wardrobe.png",
	"4648_pupil":                      "http://reading-cdn.dubaner.com/resource/word/image/G6S2U1_pupil.png",
	"4649_quite":                      "http://reading-cdn.dubaner.com/resource/word/image/G6S2U1_quite.png",
	"4650_scarf":                      "http://reading-cdn.dubaner.com/resource/word/image/G6S2U1_scarf.png",
	"4651_live":                       "http://reading-cdn.dubaner.com/resource/word/image/G6S2U1_live.png",
	"4652_meet":                       "http://reading-cdn.dubaner.com/resource/word/image/G6S2U1_meet.png",
	"4653_art gallery":                "http://reading-cdn.dubaner.com/resource/word/image/G6S2U2_art_gallery.png",
	"4654_public library":             "http://reading-cdn.dubaner.com/resource/word/image/G6S2U2_public_library.png",
	"4655_Queen's Park":               "http://reading-cdn.dubaner.com/resource/word/image/G6S2U2_Queen's_Park.png",
	"4656_show around":                "http://reading-cdn.dubaner.com/resource/word/image/G6S2U2_show_around.png",
	"4657_Lake Ontario":               "http://reading-cdn.dubaner.com/resource/word/image/G6S2U2_Lake_Ontario.png",
	"4658_stadium":                    "http://reading-cdn.dubaner.com/resource/word/image/G6S2U2_stadium.png",
	"4659_downtown":                   "http://reading-cdn.dubaner.com/resource/word/image/G6S2U2_downtown.png",
	"4660_top":                        "http://reading-cdn.dubaner.com/resource/word/image/G6S2U3_top.png",
	"4661_at least":                   "http://reading-cdn.dubaner.com/resource/word/image/G6S2U3_at_least.png",
	"4662_volunteer":                  "http://reading-cdn.dubaner.com/resource/word/image/G6S2U3_volunteer.png",
	"4663_habit":                      "http://reading-cdn.dubaner.com/resource/word/image/G6S2U3_habit.png",
	"4664_sandwich":                   "http://reading-cdn.dubaner.com/resource/word/image/G6S2U3_sandwich.png",
	"4665_idea":                       "http://reading-cdn.dubaner.com/resource/word/image/G6S2U3_idea.png",
	"4666_less":                       "http://reading-cdn.dubaner.com/resource/word/image/G6S2U3_less.png",
	"4667_together":                   "http://reading-cdn.dubaner.com/resource/word/image/G6S2U4_together.png",
	"4668_beaver":                     "http://reading-cdn.dubaner.com/resource/word/image/G6S2U4_beaver.png",
	"4669_raccoon":                    "http://reading-cdn.dubaner.com/resource/word/image/G6S2U4_raccoon.png",
	"4670_hockey":                     "http://reading-cdn.dubaner.com/resource/word/image/G6S2U4_hockey.png",
	"4671_special":                    "http://reading-cdn.dubaner.com/resource/word/image/G6S2U4_special.png",
	"4672_talk about":                 "http://reading-cdn.dubaner.com/resource/word/image/G6S2U4_talk_about.png",
	"4673_moose":                      "http://reading-cdn.dubaner.com/resource/word/image/G6S2U4_moose.png",
	"4674_frog":                       "http://reading-cdn.dubaner.com/resource/word/image/G6S2U5_frog.png",
	"4675_roast turkey":               "http://reading-cdn.dubaner.com/resource/word/image/G6S2U5_roast_turkey.png",
	"4676_wild goose":                 "http://reading-cdn.dubaner.com/resource/word/image/G6S2U5_wild_goose.png",
	"4677_squirrel":                   "http://reading-cdn.dubaner.com/resource/word/image/G6S2U5_squirrel.png",
	"4678_countryside":                "http://reading-cdn.dubaner.com/resource/word/image/G6S2U5_countryside.png",
	"4679_swan":                       "http://reading-cdn.dubaner.com/resource/word/image/G6S2U5_swan.png",
	"4680_Thanksgiving":               "http://reading-cdn.dubaner.com/resource/word/image/G6S2U5_Thanksgiving.png",
	"4681_amazing":                    "http://reading-cdn.dubaner.com/resource/word/image/G6S2U6_amazing.png",
	"4682_hot pot":                    "http://reading-cdn.dubaner.com/resource/word/image/G6S2U6_hot_pot.png",
	"4683_shopping centre":            "http://reading-cdn.dubaner.com/resource/word/image/G6S2U6_shopping_centre.png",
	"4684_shopping mall":              "http://reading-cdn.dubaner.com/resource/word/image/G6S2U6_shopping_mall.png",
	"4685_English-Chinese dictionary": "http://reading-cdn.dubaner.com/resource/word/image/G6S2U6_English-Chinese_dictionary.png",
}
