info:
  contact: {}
  license: {}
paths:
  /test/form_post:
    post:
      description: 获取form表单提交的参数
      parameters:
      - description: 名称
        in: query
        name: name
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
  /test/getuser/{id}:
    get:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: test
swagger: "2.0"
